test-build.sh

Added script for running test builds of all images

---

0.12/Dockerfile
0.12/onbuild/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile

Update Node.js to 0.12.5 as well

---

0.10/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile
0.8/Dockerfile
0.8/slim/Dockerfile
0.8/wheezy/Dockerfile

Update npm to 2.13.3

---

0.10/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile

Updates npm. Build test passes!

Update npm to 2.14.1

---

generate-stackbrew-library.sh

node:4 should be an alias for node:4.0.0
node:0 should be an alias for nod:0.12.7

fix node:0 alias tag and add node:4 alias tag. Fixes #43

---

4.1/Dockerfile
4.1/onbuild/Dockerfile
4.1/slim/Dockerfile
4.1/wheezy/Dockerfile
generate-stackbrew-library.sh

Updates the 4.* directory, docker files and generate-stackbrew-library.sh file for 4.1.
Test build passes!

Update for node v4.1.0

---

4.1/Dockerfile
4.1/onbuild/Dockerfile
4.1/slim/Dockerfile
4.1/wheezy/Dockerfile

Release proposal: https://github.com/nodejs/node/issues/2943

Update to 4.1.1

---

4.1/Dockerfile
4.1/onbuild/Dockerfile
4.1/slim/Dockerfile
4.1/wheezy/Dockerfile

Release notes: https://nodejs.org/en/blog/release/v4.1.2/

Update to 4.1.2

---

4.2/Dockerfile
4.2/onbuild/Dockerfile
4.2/slim/Dockerfile
4.2/wheezy/Dockerfile
generate-stackbrew-library.sh

LTS Release 'Argon'.
Reference: https://github.com/nodejs/node/pull/3258

Upgrade to 4.2.0

---

LICENSE

Transfer the license/copyright ownership of this project to Node.js contributors.
// ping @chorrell

Transfer license ownership to Node.js contributors

---

README.md

Update the project README.md with lots of good documentation. This is based on the work in docker-library/docs#172 and nodejs/docker-iojs#52

Copy README.md from nodejs/docker-iojs

---

5.0/Dockerfile
5.0/onbuild/Dockerfile
5.0/slim/Dockerfile
5.0/wheezy/Dockerfile
generate-stackbrew-library.sh

Reference: https://github.com/nodejs/node/pull/3466

Add node-v5.0.0

---

4.2/Dockerfile
4.2/onbuild/Dockerfile
4.2/slim/Dockerfile
4.2/wheezy/Dockerfile

Reference: https://github.com/nodejs/node/pull/3588

Upgrade node-v4.2.1 to node-v4.2.2

---

5.1/Dockerfile
5.1/onbuild/Dockerfile
5.1/slim/Dockerfile
5.1/wheezy/Dockerfile
generate-stackbrew-library.sh

Reference: https://github.com/nodejs/node/pull/3736

Upgrade node-v5.0.0 to node-v5.1.0

---

0.12/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile

Updating npm to v3 was well intentioned but problematic.

Don't update npm in 0.12. Fixes #72.

---

0.10/Dockerfile
0.10/onbuild/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/onbuild/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile
4.2/Dockerfile
4.2/onbuild/Dockerfile
4.2/slim/Dockerfile
4.2/wheezy/Dockerfile
5.1/Dockerfile
5.1/onbuild/Dockerfile
5.1/slim/Dockerfile
5.1/wheezy/Dockerfile

This updates The Node.js images to:
- 0.10.41
- 0.12.9
- 4.2.3
- 5.1.1

0.10.41 0.12.9 4.2.3 5.1.1

---

5.4/Dockerfile
5.4/onbuild/Dockerfile
5.4/slim/Dockerfile
5.4/wheezy/Dockerfile
generate-stackbrew-library.sh

Update Node to 5.4.0
Related: nodejs/node#4547

Update Node to 5.4.0

---

4.2/Dockerfile
4.2/onbuild/Dockerfile
4.2/slim/Dockerfile
4.2/wheezy/Dockerfile

Update Node to 4.2.5

---

5.5/Dockerfile
5.5/onbuild/Dockerfile
5.5/slim/Dockerfile
5.5/wheezy/Dockerfile
generate-stackbrew-library.sh

Related: https://github.com/nodejs/node/pull/4742

Update Node to 5.5.0

---

4.2/Dockerfile
4.2/onbuild/Dockerfile
4.2/slim/Dockerfile
4.2/wheezy/Dockerfile

Update Node to 4.2.6

---

0.10/Dockerfile
0.10/onbuild/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/onbuild/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile

Update Node.js to v0.10.42 and v0.12.10

---

5.6/Dockerfile
5.6/onbuild/Dockerfile
5.6/slim/Dockerfile
5.6/wheezy/Dockerfile
generate-stackbrew-library.sh

This just mimics this PR (https://github.com/nodejs/docker-node/pull/90) for the latest release.

update node to 5.6

---

4.3/Dockerfile
4.3/onbuild/Dockerfile
4.3/slim/Dockerfile
4.3/wheezy/Dockerfile

Updates 4.x.x to v4.3.1.
Reference:
https://nodejs.org/en/blog/release/v4.3.1/

Update to  v4.3.1

---

0.10/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile
4.3/Dockerfile
4.3/slim/Dockerfile
4.3/wheezy/Dockerfile
5.7/Dockerfile
5.7/slim/Dockerfile
5.7/wheezy/Dockerfile

See also docker-library/official-images#1420.

Fix "gpg" usage to stop relying on deprecated and insecure behavior

---

4.3/Dockerfile
4.3/onbuild/Dockerfile
4.3/slim/Dockerfile
4.3/wheezy/Dockerfile

Update for Node.js v4.3.2.
Test build via test-build.sh  looks good!

Update for v4.3.2

---

0.12/Dockerfile
0.12/onbuild/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile

Reference:
- https://nodejs.org/en/blog/release/v0.12.12/

Update to Node.js 0.12.12

---

4.4/Dockerfile
4.4/onbuild/Dockerfile
4.4/slim/Dockerfile
4.4/wheezy/Dockerfile
generate-stackbrew-library.sh

Updates to Node.js v4.4.0
See:
- https://github.com/nodejs/node/pull/5301

Update to v4.4.0

---

5.8/Dockerfile
5.8/onbuild/Dockerfile
5.8/slim/Dockerfile
5.8/wheezy/Dockerfile
generate-stackbrew-library.sh

Test build looks good.
Reference:
- https://nodejs.org/en/blog/release/v5.8.0/
- https://github.com/nodejs/node/pull/5559

Upate to v5.8.0. Fixes #119

---

5.9/Dockerfile
5.9/onbuild/Dockerfile
5.9/slim/Dockerfile
5.9/wheezy/Dockerfile

Test build looks good.
See:
- https://nodejs.org/en/blog/release/v5.9.0/
- https://github.com/nodejs/node/pull/5702

Update to v5.9.0. See #123

---

generate-stackbrew-library.sh

Missed the update to generate-stackbrew-library.sh from previous pull request

Update for 5.9.0

---

5.9/Dockerfile
5.9/onbuild/Dockerfile
5.9/slim/Dockerfile
5.9/wheezy/Dockerfile

Update to  v5.9.1. See #128

---

4.4/Dockerfile
4.4/onbuild/Dockerfile
4.4/slim/Dockerfile
4.4/wheezy/Dockerfile

Update to v4.4.2

---

test-build.sh

In addition to testing that the images build correctly, now test-build.sh also validates that Node executes successfully, and that it is the expected version.
Also fixed some inconsistent whitespace.

Enhance test-build.sh to also perform simple execution tests

---

5.10/Dockerfile
5.10/onbuild/Dockerfile
5.10/slim/Dockerfile
5.10/wheezy/Dockerfile

Test build looks good:
https://travis-ci.org/chorrell/docker-node/builds/121039629

Update to v5.10.1. See #142

---

4.4/Dockerfile
4.4/onbuild/Dockerfile
4.4/slim/Dockerfile
4.4/wheezy/Dockerfile

Update for Node.js v4.4.3

---

0.10/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile
5.11/Dockerfile
5.11/onbuild/Dockerfile
5.11/slim/Dockerfile
5.11/wheezy/Dockerfile

Also formatting tweaks to make 0.10 and 0.12 consistent with the other
images
Test build looks good!
https://travis-ci.org/chorrell/docker-node/builds/124888504

Update for v5.11.0

---

test-build.sh

Removes -q flag when building test images

Make test builds more debugable

---

6.0/Dockerfile
6.0/onbuild/Dockerfile
6.0/slim/Dockerfile
6.0/wheezy/Dockerfile
generate-stackbrew-library.sh

Update for Node.js v6.0.0

---

GOVERNANCE.md

See: https://github.com/nodejs/TSC/issues/92

Update DCO to v1.1

---

update.sh

Fix update.sh to account for default Dockerfile

---

6.2/Dockerfile
6.2/onbuild/Dockerfile
6.2/slim/Dockerfile
6.2/wheezy/Dockerfile
generate-stackbrew-library.sh

Update for v6.2.0

---

6.2/Dockerfile
6.2/onbuild/Dockerfile
6.2/slim/Dockerfile
6.2/wheezy/Dockerfile

Update for v6.2.1

---

6.2/Dockerfile
6.2/onbuild/Dockerfile
6.2/slim/Dockerfile
6.2/wheezy/Dockerfile

See https://github.com/nodejs/node/pull/7323

Update for v6.2.2

---

0.10/Dockerfile
0.10/onbuild/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/onbuild/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile
4.4/Dockerfile
4.4/onbuild/Dockerfile
4.4/slim/Dockerfile
4.4/wheezy/Dockerfile
5.12/Dockerfile
5.12/onbuild/Dockerfile
5.12/slim/Dockerfile
5.12/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://github.com/nodejs/LTS/issues/114
- https://nodejs.org/en/blog/release/v0.10.46/
- https://nodejs.org/en/blog/release/v0.12.15/
- https://nodejs.org/en/blog/release/v4.4.6/
- https://nodejs.org/en/blog/release/v5.12.0/
Closes #201

Update for Node.js v0.10.46, v0.12.15, v4.4.6 and v5.12.0

---

4.4/Dockerfile
4.4/onbuild/Dockerfile
4.4/slim/Dockerfile
4.4/wheezy/Dockerfile

See:
- https://github.com/nodejs/LTS/issues/114
- https://github.com/nodejs/node/pull/7395

Update to Node.js v4.4.7. Fixes #202.

---

docs/BestPractices.md

Add commas and change "inn" to "in".

docs: Fix minor typos in BestPractices.md

---

6.4/Dockerfile
6.4/onbuild/Dockerfile
6.4/slim/Dockerfile
6.4/wheezy/Dockerfile
generate-stackbrew-library.sh

Update for Node.js v6.4.0

---

4.5/Dockerfile
4.5/onbuild/Dockerfile
4.5/slim/Dockerfile
4.5/wheezy/Dockerfile
generate-stackbrew-library.sh

See: 
- https://nodejs.org/en/blog/release/v4.5.0/

Update for Node.js v4.5.0

---

6.5/Dockerfile
6.5/onbuild/Dockerfile
6.5/slim/Dockerfile
6.5/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v6.5.0/

Update for Node.js v6.5.0

---

6.6/Dockerfile
6.6/onbuild/Dockerfile
6.6/slim/Dockerfile
6.6/wheezy/Dockerfile
generate-stackbrew-library.sh

See https://nodejs.org/en/blog/release/v6.6.0/

Update for Node.js v6.6.0

---

0.10/onbuild/Dockerfile
0.12/onbuild/Dockerfile
4.5/onbuild/Dockerfile
6.6/onbuild/Dockerfile

Adds `ARG  NODE_ENV` to the onbuild docker files.

Add NODE_ENV ARG to all Dockerfiles

---

update.sh

This adds some improvements that I borrowed from the recently updated generate-stackbrew-library.sh script.

Update script improvements

---

6.8/Dockerfile
6.8/onbuild/Dockerfile
6.8/slim/Dockerfile
6.8/wheezy/Dockerfile
generate-stackbrew-library.sh

See: https://nodejs.org/en/blog/release/v6.8.0/

Update for Node.js v6.8.0

---

6.8/Dockerfile
6.8/onbuild/Dockerfile
6.8/slim/Dockerfile
6.8/wheezy/Dockerfile

See:
- https://nodejs.org/en/blog/release/v6.8.1/

Update for Node.js v6.8.1

---

0.12/Dockerfile
0.12/onbuild/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile

This is part of the October Security release:
- https://nodejs.org/en/blog/vulnerability/october-2016-security-releases/
- https://nodejs.org/en/blog/release/v0.12.17/

Update for Node.js v0.12.17

---

0.10/Dockerfile
0.10/onbuild/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile

Part of the October Security update:
- https://nodejs.org/en/blog/vulnerability/october-2016-security-releases/

Updated for v0.10.48

---

4.6/Dockerfile
4.6/onbuild/Dockerfile
4.6/slim/Dockerfile
4.6/wheezy/Dockerfile

Part of the October Security updates:
- https://nodejs.org/en/blog/vulnerability/october-2016-security-releases/
- https://github.com/nodejs/docker-node/issues/247

Update for Node.js v4.6.1

---

6.9/Dockerfile
6.9/onbuild/Dockerfile
6.9/slim/Dockerfile
6.9/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v6.9.0/
- https://nodejs.org/en/blog/vulnerability/october-2016-security-releases/

Update for Node.js v6.9.0 LTS (boron)

---

6.9/Dockerfile
6.9/onbuild/Dockerfile
6.9/slim/Dockerfile
6.9/wheezy/Dockerfile

See:
- https://nodejs.org/en/blog/release/v6.9.1/

Update for Node.js v6.9.1

---

7.0/Dockerfile
7.0/onbuild/Dockerfile
7.0/slim/Dockerfile
7.0/wheezy/Dockerfile
generate-stackbrew-library.sh

See: https://nodejs.org/en/blog/release/v7.0.0/

Add Node.js v7.0.0

---

0.10/Dockerfile
0.10/slim/Dockerfile
0.10/wheezy/Dockerfile
0.12/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile
4.6/Dockerfile
4.6/slim/Dockerfile
4.6/wheezy/Dockerfile
6.9/Dockerfile
6.9/slim/Dockerfile
6.9/wheezy/Dockerfile
7.0/Dockerfile
7.0/slim/Dockerfile
7.0/wheezy/Dockerfile

Add non-root "node" user to all Docker images

---

4.6/Dockerfile
4.6/onbuild/Dockerfile
4.6/slim/Dockerfile
4.6/wheezy/Dockerfile
7.1/Dockerfile
7.1/onbuild/Dockerfile
7.1/slim/Dockerfile
7.1/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v7.1.0/
- https://nodejs.org/en/blog/release/v4.6.2/

Update for V7.10 and v4.6.2

---

README.md

Added LaurentGoderre as a collaborator

---

docs/BestPractices.md

Wrong username mentioned in docs

---

update.sh

Remove mention of 0.10 from update script

---

docs/BestPractices.md

I think user home dir works better instead of `-w "/usr/src/app"` use `-w "/home/node/app"`

In docs example use home dir as work dir

---

README.md

Added the alpine docs to the readme

---

.travis.yml
4.7/Dockerfile
4.7/alpine/Dockerfile
4.7/onbuild/Dockerfile
4.7/slim/Dockerfile
4.7/wheezy/Dockerfile
7.2/Dockerfile
7.2/alpine/Dockerfile
7.2/onbuild/Dockerfile
7.2/slim/Dockerfile
7.2/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v7.2.1/
- https://nodejs.org/en/blog/release/v4.7.0/

Update for Node.js v7.2.1 and v4.7.0

---

.travis.yml
7.3/Dockerfile
7.3/alpine/Dockerfile
7.3/onbuild/Dockerfile
7.3/slim/Dockerfile
7.3/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v7.3.0/

Update for Node.js v7.3.0

---

0.12/Dockerfile
0.12/onbuild/Dockerfile
0.12/slim/Dockerfile
0.12/wheezy/Dockerfile

See:
- https://nodejs.org/en/blog/release/v0.12.18/

Update for Node.js v0.12.18

---

docs/BestPractices.md

Added entry to **Non-root User** section to show adding user & group in the alpine variant since the commands are a little different.
See [mhart/alpine-node#48](https://github.com/mhart/alpine-node/issues/48) for more info.

Update BestPractices.md with alpine user

---

4.7/Dockerfile
4.7/alpine/Dockerfile
4.7/onbuild/Dockerfile
4.7/slim/Dockerfile
4.7/wheezy/Dockerfile
6.9/Dockerfile
6.9/alpine/Dockerfile
6.9/onbuild/Dockerfile
6.9/slim/Dockerfile
6.9/wheezy/Dockerfile

See:
- https://nodejs.org/en/blog/release/v4.7.1/
- https://nodejs.org/en/blog/release/v6.9.3/

Update for Node.js v4.7.1 and v6.9.3

---

.travis.yml
7.4/Dockerfile
7.4/alpine/Dockerfile
7.4/onbuild/Dockerfile
7.4/slim/Dockerfile
7.4/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v7.4.0/

Update for Node.js v7.4.0

---

4.7/Dockerfile
4.7/alpine/Dockerfile
4.7/onbuild/Dockerfile
4.7/slim/Dockerfile
4.7/wheezy/Dockerfile
6.9/Dockerfile
6.9/alpine/Dockerfile
6.9/onbuild/Dockerfile
6.9/slim/Dockerfile
6.9/wheezy/Dockerfile

See:
- https://nodejs.org/en/blog/release/v4.7.2/
- https://nodejs.org/en/blog/release/v6.9.4/
- https://github.com/nodejs/build/issues/586

Update for Node.js v4.7.2 and v6.9.4

---

.travis.yml
7.5/Dockerfile
7.5/alpine/Dockerfile
7.5/onbuild/Dockerfile
7.5/slim/Dockerfile
7.5/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v7.5.0/
- https://nodejs.org/en/blog/vulnerability/openssl-january-2017/
- https://github.com/nodejs/docker-node/issues/314

Update for Node.js v7.5.0

---

docs/BestPractices.md

Document init wrapper

---

.travis.yml
4.8/Dockerfile
4.8/alpine/Dockerfile
4.8/onbuild/Dockerfile
4.8/slim/Dockerfile
4.8/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v4.8.0/

Update for Node.js v4.8.0

---

.travis.yml
6.10/Dockerfile
6.10/alpine/Dockerfile
6.10/onbuild/Dockerfile
6.10/slim/Dockerfile
6.10/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v6.10.0/

Update for Node.js v6.10.0

---

4.8/Dockerfile
4.8/alpine/Dockerfile
4.8/slim/Dockerfile
4.8/wheezy/Dockerfile
6.10/Dockerfile
6.10/alpine/Dockerfile
6.10/slim/Dockerfile
6.10/wheezy/Dockerfile
7.6/Dockerfile
7.6/alpine/Dockerfile
7.6/slim/Dockerfile
7.6/wheezy/Dockerfile
Dockerfile-alpine.template
Dockerfile-slim.template
Dockerfile-wheezy.template
Dockerfile.template

Build stability improvements, as requested here: https://github.com/docker-library/official-images/pull/2703#issuecomment-283201291

Build stability improvements (curl & gpg)

---

README.md

I think we should mention what is installed in the Image. Should we add some links or write some more about the different parts?

Mention yarn in the README.md

---

7.7/Dockerfile
7.7/alpine/Dockerfile
7.7/onbuild/Dockerfile
7.7/slim/Dockerfile
7.7/wheezy/Dockerfile

See: https://nodejs.org/en/blog/release/v7.7.2/

Update for Node.js v7.7.2

---

7.7/Dockerfile
7.7/alpine/Dockerfile
7.7/onbuild/Dockerfile
7.7/slim/Dockerfile
7.7/wheezy/Dockerfile

See: https://nodejs.org/en/blog/release/v7.7.3/

Update for Node.js v7.7.3

---

4.8/Dockerfile
4.8/alpine/Dockerfile
4.8/onbuild/Dockerfile
4.8/slim/Dockerfile
4.8/wheezy/Dockerfile
6.10/Dockerfile
6.10/alpine/Dockerfile
6.10/onbuild/Dockerfile
6.10/slim/Dockerfile
6.10/wheezy/Dockerfile

See:
- https://nodejs.org/en/blog/release/v4.8.1/
- https://nodejs.org/en/blog/release/v6.10.1/

Update for Node.js v4.8.1 and v6.10.1

---

7.7/Dockerfile
7.7/alpine/Dockerfile
7.7/onbuild/Dockerfile
7.7/slim/Dockerfile
7.7/wheezy/Dockerfile

See:
- https://nodejs.org/en/blog/release/v7.7.4/

Update for Node.js v7.7.4

---

4.8/alpine/Dockerfile
6.10/alpine/Dockerfile
7.7/alpine/Dockerfile

Completes #307 and partially replaces #369

Updated the alpine images with the new group and user

---

.travis.yml
7.8/Dockerfile
7.8/alpine/Dockerfile
7.8/onbuild/Dockerfile
7.8/slim/Dockerfile
7.8/wheezy/Dockerfile
generate-stackbrew-library.sh

See:
- https://nodejs.org/en/blog/release/v7.8.0/

Update for Node.js v7.8.0. Closes #369

---

4.8/Dockerfile
4.8/alpine/Dockerfile
4.8/slim/Dockerfile
4.8/wheezy/Dockerfile
6.10/Dockerfile
6.10/alpine/Dockerfile
6.10/slim/Dockerfile
6.10/wheezy/Dockerfile
7.8/Dockerfile
7.8/alpine/Dockerfile
7.8/slim/Dockerfile
7.8/wheezy/Dockerfile

See: https://github.com/yarnpkg/yarn/releases/tag/v0.22.0

Update for yarn 0.22.0

---

.travis.yml
7.9/Dockerfile
7.9/alpine/Dockerfile
7.9/onbuild/Dockerfile
7.9/slim/Dockerfile
7.9/wheezy/Dockerfile
generate-stackbrew-library.sh

https://nodejs.org/en/blog/release/v7.9.0/
Not sure id anything else is needed?
I tried to run `update.sh` (just `./update.sh 7.9.0`), but that did nothing, so the changes here were done manually. Maybe a CONTRIBUTING.md should be added?
EDIT: Doing `git mv 7.8 7.9; ./update.sh` worked. Should the directories here be just major and not minor? Can be discussed in separate issue, I suppose. EDIT2: #322

Update for node 7.9.0

---

4.8/Dockerfile
4.8/alpine/Dockerfile
4.8/slim/Dockerfile
4.8/wheezy/Dockerfile
6.10/Dockerfile
6.10/alpine/Dockerfile
6.10/slim/Dockerfile
6.10/wheezy/Dockerfile
7.9/Dockerfile
7.9/alpine/Dockerfile
7.9/slim/Dockerfile
7.9/wheezy/Dockerfile

Update yarn version

---

4.8/Dockerfile
4.8/alpine/Dockerfile
4.8/onbuild/Dockerfile
4.8/slim/Dockerfile
4.8/wheezy/Dockerfile
6.10/Dockerfile
6.10/alpine/Dockerfile
6.10/onbuild/Dockerfile
6.10/slim/Dockerfile
6.10/wheezy/Dockerfile

https://nodejs.org/en/blog/release/v4.8.3/
https://nodejs.org/en/blog/release/v6.10.3/

Node update

---

generate-stackbrew-library.sh

Latest tag wasn't updated properly in #392

Fix latest tag

---

.travis.yml
6.11/Dockerfile
6.11/alpine/Dockerfile
6.11/onbuild/Dockerfile
6.11/slim/Dockerfile
6.11/wheezy/Dockerfile
generate-stackbrew-library.sh

Ref nodejs/node#13059
Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.11.0

Update for Node v6.11.0 LTS

---

8.1/Dockerfile
8.1/alpine/Dockerfile
8.1/onbuild/Dockerfile
8.1/slim/Dockerfile
8.1/wheezy/Dockerfile

https://nodejs.org/en/blog/release/v8.1.1/

Update to node 8.1.1

---

8.1/Dockerfile
8.1/alpine/Dockerfile
8.1/onbuild/Dockerfile
8.1/slim/Dockerfile
8.1/wheezy/Dockerfile

https://nodejs.org/en/blog/release/v8.1.2/
See nodejs/node#13667

Update to node 8.1.2

---

.travis.yml
generate-stackbrew-library.sh
test-build.sh
update.sh

Add Shellcheck to Travis and fix existing checks

---

test-build.sh

Fatal will exit 1 so we can just make it shorter 🚀

Refactor to make test-build.sh shorter

---

.travis.yml
README.md

This can help us keep "Table of Contents" in README.md up-to-date

Refactor .travis.yml and add doctoc check

---

.travis.yml
8.2/Dockerfile
8.2/alpine/Dockerfile
8.2/onbuild/Dockerfile
8.2/slim/Dockerfile
8.2/wheezy/Dockerfile
generate-stackbrew-library.sh

https://nodejs.org/en/blog/release/v8.2.0/
Blog post not available yet, but https://nodejs.org/dist/v8.2.0/node-v8.2.0-linux-x64.tar.xz exists.
EDIT: Blog post up

Update Node to 8.2.0

---

4.8/Dockerfile
4.8/slim/Dockerfile
4.8/stretch/Dockerfile
4.8/wheezy/Dockerfile
6.11/Dockerfile
6.11/slim/Dockerfile
6.11/stretch/Dockerfile
6.11/wheezy/Dockerfile
7.10/Dockerfile
7.10/slim/Dockerfile
7.10/stretch/Dockerfile
7.10/wheezy/Dockerfile
8.2/Dockerfile
8.2/slim/Dockerfile
8.2/stretch/Dockerfile
8.2/wheezy/Dockerfile

I ran `./update` and removed yarn version changes from the diff.
/cc @yhwang

Update all dockerfiles with template changes

---

README.md

There was nothing in the "Usage" section so I removed it

Remove the "Usage" section

---

4.8/Dockerfile
4.8/slim/Dockerfile
4.8/stretch/Dockerfile
6.11/Dockerfile
6.11/slim/Dockerfile
6.11/stretch/Dockerfile
7.10/Dockerfile
7.10/slim/Dockerfile
7.10/stretch/Dockerfile
8.2/Dockerfile
8.2/slim/Dockerfile
8.2/stretch/Dockerfile

Oops...
https://github.com/docker-library/official-images/pull/3297#issuecomment-321311735

Regenerate dockerfiles to update case statements

---

8.3/Dockerfile
8.3/alpine/Dockerfile
8.3/onbuild/Dockerfile
8.3/slim/Dockerfile
8.3/stretch/Dockerfile
8.3/wheezy/Dockerfile
generate-stackbrew-library.sh

https://nodejs.org/en/blog/release/v8.3.0/

Update for node 8.3

---

docs/BestPractices.md

Just a little typo i saw while I was reading.

update docs/BestPractices.md - typo

---

4.8/architectures
4.8/slim/Dockerfile
6.11/slim/Dockerfile
7.10/slim/Dockerfile
8.3/slim/Dockerfile
Dockerfile-slim.template

Add arm64 to slim and 4.8

---

6.11/Dockerfile
6.11/alpine/Dockerfile
6.11/onbuild/Dockerfile
6.11/slim/Dockerfile
6.11/stretch/Dockerfile
6.11/wheezy/Dockerfile

https://nodejs.org/en/blog/release/v6.11.3/

Add Node.js v6.11.3

---

8.6/Dockerfile
8.6/alpine/Dockerfile
8.6/onbuild/Dockerfile
8.6/slim/Dockerfile
8.6/stretch/Dockerfile
8.6/wheezy/Dockerfile
generate-stackbrew-library.sh

https://nodejs.org/en/blog/release/v8.6.0/
Blogpost not up yet

Upgrade to node 8.6

---

README.md

Switched to a snippet that works out of the box with a package.json that has a start script.

README: Updated the docker-compose example

---

docs/BestPractices.md

Added a section about global npm install

---

8.7/Dockerfile
8.7/alpine/Dockerfile
8.7/onbuild/Dockerfile
8.7/slim/Dockerfile
8.7/stretch/Dockerfile
8.7/wheezy/Dockerfile
generate-stackbrew-library.sh

https://nodejs.org/en/blog/release/v8.7.0/

Upgrade to node 8.7

---

8.8/Dockerfile
8.8/alpine/Dockerfile
8.8/onbuild/Dockerfile
8.8/slim/Dockerfile
8.8/stretch/Dockerfile
8.8/wheezy/Dockerfile

Fixes a regression with the 8.8.0 security release :-) 
- Fix timeout with null handle issue. This is a regression in Node 8.8.0 #16489
See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.8.1

Upgrade to node 8.8.1

---

docs/BestPractices.md

tiny word fix

---

generate-stackbrew-library.sh

I'm pretty sure this is the only change required  -- I didn't see anything in the README.md that needed touching.

Add carbon tag. Closes #502

---

8.9/Dockerfile
8.9/alpine/Dockerfile
8.9/onbuild/Dockerfile
8.9/slim/Dockerfile
8.9/stretch/Dockerfile
8.9/wheezy/Dockerfile
generate-stackbrew-library.sh

https://github.com/nodejs/node/releases/tag/v8.9.0

Update v8.x to v8.9.0

---

.travis.yml
9.0/Dockerfile
9.0/alpine/Dockerfile
9.0/onbuild/Dockerfile
9.0/slim/Dockerfile
9.0/stretch/Dockerfile
9.0/wheezy/Dockerfile
generate-stackbrew-library.sh

Ignore https://github.com/nodejs/docker-node/pull/565/commits/58b51fc8a28a6084cde6be419bdeee4afdda9aba please, it should be disappeared once #563 passed the CI and been merged, I added it here just to prevent commit conflict :)

Add Nodejs 9.0.0

---

9/Dockerfile
9/alpine/Dockerfile
9/onbuild/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile

See: https://nodejs.org/en/blog/release/v9.3.0/

Update for Node.js v9.3.0

---

6/Dockerfile
6/alpine/Dockerfile
6/onbuild/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
6/wheezy/Dockerfile

See: https://nodejs.org/en/blog/release/v6.12.3/

Update for Node.js v6.12.3

---

8/Dockerfile
8/alpine/Dockerfile
8/onbuild/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile
8/wheezy/Dockerfile

https://nodejs.org/en/blog/release/v8.9.4/

Update for Node.js v8.9.4

---

9/Dockerfile
9/alpine/Dockerfile
9/onbuild/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V9.md#9.4.0

Update node.js v9.4.0

---

docs/BestPractices.md

Fix typo in "Non-root User" section

---

9/Dockerfile
9/alpine/Dockerfile
9/onbuild/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile

See: https://nodejs.org/en/blog/release/v9.5.0/

Update for Node.js v9.5.0

---

6/Dockerfile
6/alpine/Dockerfile
6/onbuild/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
6/wheezy/Dockerfile

https://github.com/nodejs/node/releases/tag/v6.13.0

Update for node.js v6.13.0

---

update.sh

This should make the version update process much more faster :)

Futher parallelize update.sh for different variants

---

9/Dockerfile
9/alpine/Dockerfile
9/onbuild/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile

https://github.com/nodejs/node/releases/tag/v9.6.0

Update for node.js v9.6.0

---

6/Dockerfile
6/alpine/Dockerfile
6/onbuild/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
6/wheezy/Dockerfile

Also updates yarn to 1.5.1
See: https://nodejs.org/en/blog/release/v6.13.1/

Update for Node.js v6.13.1

---

8/Dockerfile
8/alpine/Dockerfile
8/onbuild/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile
8/wheezy/Dockerfile

See: https://nodejs.org/en/blog/release/v8.10.0/
Also updates yarn to 1.5.1

Update for Node.js v8.10.0

---

9/Dockerfile
9/alpine/Dockerfile
9/onbuild/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile

See: https://nodejs.org/en/blog/release/v9.8.0/

Update for Node.js v9.8.0

---

Dockerfile-alpine.template
Dockerfile-slim.template
Dockerfile-stretch.template
Dockerfile-wheezy.template
Dockerfile.template

Fix yarn directory creation step

---

4/Dockerfile
4/alpine/Dockerfile
4/slim/Dockerfile
4/stretch/Dockerfile
4/wheezy/Dockerfile
6/Dockerfile
6/alpine/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
6/wheezy/Dockerfile
8/Dockerfile
8/alpine/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile
8/wheezy/Dockerfile
9/Dockerfile
9/alpine/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile

Update yarn w/ symbolic-linked directory

---

4/Dockerfile
4/alpine/Dockerfile
4/slim/Dockerfile
4/stretch/Dockerfile
4/wheezy/Dockerfile
6/Dockerfile
6/alpine/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
6/wheezy/Dockerfile
8/Dockerfile
8/alpine/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile
8/wheezy/Dockerfile
9/Dockerfile
9/alpine/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile
Dockerfile-alpine.template
Dockerfile-slim.template
Dockerfile-stretch.template
Dockerfile-wheezy.template
Dockerfile.template
test-build.sh

Fixes #649 
I need to test the image properly, so wait or test it by yourself.

Fixed symbolic links to yarn and yarnpkg

---

chakracore/8/Dockerfile
chakracore/Dockerfile.template

Matched the behavior used for node-v8

Update yarn script for chakracore

---

test-build.sh

Prevent the building of the default variant for each Travis stage

---

9/Dockerfile
9/alpine/Dockerfile
9/onbuild/Dockerfile
9/slim/Dockerfile
9/stretch/Dockerfile
9/wheezy/Dockerfile

- https://github.com/nodejs/node/releases/tag/v9.11.0

Update node.js v9.x to v9.11.1

---

travis.yml.template

Update travis.yml.template, remove manual ShellCheck installation

---

6/Dockerfile
6/alpine/Dockerfile
6/onbuild/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
6/wheezy/Dockerfile

- https://github.com/nodejs/node/releases/tag/v6.14.2

Update node.js v6.x to 6.14.2 with Yarn v1.6.0

---

10/Dockerfile
10/alpine/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile
10/wheezy/Dockerfile

- https://github.com/nodejs/node/releases/tag/v10.1.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md

Update node.js v10.0.0 to v10.1.0

---

.editorconfig
.travis.yml
docs/BestPractices.md
update.sh

Add EditorConfig with common settings and settings for `*.sh`, should extend to other files soon.
cc #728

Introduce EditorConfig

---

8/Dockerfile
8/alpine/Dockerfile
8/onbuild/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile

https://nodejs.org/en/blog/release/v8.11.2/

upgrade to node 8.11.2

---

generate-stackbrew-pr.sh

See comments in https://github.com/nodejs/docker-node/pull/755

Fix typo with ${IMAGES_FILE } variable reference

---

10/Dockerfile
10/alpine/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile

See: https://nodejs.org/en/blog/release/v10.2.1/

Update for Node.js v10.2.1

---

.travis.yml
travis.yml.template

This reverts commit bffff57751a276096a35d9a3041c4412986d6e12.
The original commit breaks Docker service on Travis CI

Revert "Speed up the skipping of the build"

---

.travis.yml
travis.yml.template

We'll add it back until it works.

Drop Travis CI before_script temporarily

---

test-build.sh

Fixed the test build for chakracore

---

10/alpine/Dockerfile
10/jessie/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v10.4.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.4.0

Update node.js v10.x to v10.4.0

---

10/alpine/Dockerfile
10/jessie/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile

https://nodejs.org/en/blog/release/v10.5.0/

Update node to 10.5.0

---

config

Use space instead of tab in config file [ci skip]

---

.travis.yml
travis.yml.template

This change helps improve the flexibility of the Docker image usage.

Update `shfmt` Docker image usage on Travis CI

---

10/alpine/Dockerfile
10/jessie/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v10.8.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.8.0

Update node.js v10.x to v10.8.0 with Yarn v1.9.2

---

10/alpine/Dockerfile
10/jessie/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile
6/alpine/Dockerfile
6/jessie/Dockerfile
6/onbuild/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
8/alpine/Dockerfile
8/jessie/Dockerfile
8/onbuild/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile

@nodejs/docker could I get a review please?

Security releases: 10.9.0, 8.11.4, 6.14.4

---

8/alpine/Dockerfile
8/jessie/Dockerfile
8/onbuild/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile

https://nodejs.org/en/blog/release/v8.12.0/

fix: update to 8.12.0

---

10/alpine/Dockerfile
10/jessie/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile

https://nodejs.org/en/blog/release/v10.11.0/

Update to node 10.11.0

---

docs/BestPractices.md

Resolves issue 870
https://github.com/nodejs/docker-node/issues/870
Updated code to:
```
RUN deluser --remove-home node \
&& addgroup -S node -g 999 \
&& adduser -S -G node -u 999 node
```

update doc for alpine del node group and add user assign group

---

10/alpine/Dockerfile
10/jessie/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile

https://nodejs.org/en/blog/release/v10.12.0/

upgrade to node 10.12

---

.travis.yml
11/alpine/Dockerfile
11/jessie/Dockerfile
11/slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.0.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md

Add node.js v11.0.0 with Yarn v1.10.1

---

10/architectures
6/architectures
8/architectures

Update architectures files

---

11/alpine/Dockerfile
11/slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.1.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.1.0

Update node.js v11.x to v11.1.0 with Yarn v1.12.1

---

.travis.yml
travis.yml.template
update.sh

Auto skip unnecessary builds

---

.travis.yml
travis.yml.template

This can help debug can further improve the build skip.

Print not recognized $TRAVIS_COMMIT_RANGE on Travis CI

---

11/alpine/Dockerfile
11/slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.2.0

Update node.js v11 to v11.2.0 with Yarn v1.12.3

---

10/alpine/Dockerfile
10/jessie/Dockerfile
10/slim/Dockerfile
10/stretch/Dockerfile
11/alpine/Dockerfile
11/slim/Dockerfile
11/stretch/Dockerfile
6/alpine/Dockerfile
6/jessie/Dockerfile
6/slim/Dockerfile
6/stretch/Dockerfile
8/alpine/Dockerfile
8/jessie/Dockerfile
8/slim/Dockerfile
8/stretch/Dockerfile
Dockerfile-alpine.template
Dockerfile-jessie.template
Dockerfile-slim.template
Dockerfile-stretch.template
chakracore/10/Dockerfile
chakracore/8/Dockerfile
chakracore/Dockerfile.template

See:
- https://bugs.debian.org/913614
- https://github.com/docker-library/busybox/pull/55

Update gpg invocations to use --batch

---

.travis.yml
travis.yml.template

Fix bug of our Travis CI auto skip build scripts

---

update.sh

Update `.travis.yml` from `travis.yml.template` without touching Dockerfiles.

Add update.sh -t option to update .travis.yml only

---

10/alpine/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v10.14.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.14.1

Update nodejs v10.14.0 to v10.14.1 w/ Yarn v1.12.3

---

6/alpine/Dockerfile
6/jessie-slim/Dockerfile
6/jessie/Dockerfile
6/onbuild/Dockerfile
6/stretch-slim/Dockerfile
6/stretch/Dockerfile

https://github.com/nodejs/node/releases/tag/v6.15.1

Update node.js v6 to v6.15.1 with Yarn v1.12.3

---

.travis.yml
travis.yml.template

Use the new update.sh `-t` argument makes more sense and even a little bit faster.

Add -t arg to update.sh when testing .travis.yml consistency

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.4.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.4.0

Update node.js v11 from v11.3.0 to v11.4.0

---

10/alpine/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v10.14.2
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.14.2

Update node.js v10 from v10.14.1 to v10.14.2

---

8/alpine/Dockerfile
8/jessie-slim/Dockerfile
8/jessie/Dockerfile
8/onbuild/Dockerfile
8/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v8.14.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.14.1

Update node.js v8.x from v8.14.0 to v8.14.1

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.5.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.5.0

Update node.js v11.x from v11.4.0 to v11.5.0

---

update.sh

Old:
```
$ ./update.sh 11
Updating version 11...
Done!
```
New:
```
$ ./update.sh 11
Updating version 11...
11/alpine/Dockerfile updated!
11/stretch/Dockerfile updated!
11/stretch-slim/Dockerfile updated!
Done!
```
```
$ ./update.sh 11
Updating version 11...
11/alpine/Dockerfile is already up to date!
11/stretch/Dockerfile is already up to date!
11/stretch-slim/Dockerfile is already up to date!
Done!
```
This help us know if any of the Dockerfiles updated or not.

Add prompt msg about Dockerfile updated in update.sh

---

.travis.yml
travis.yml.template

Ref: https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

Drop deprecated Travis CI container-based env config

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.7.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.7.0

Update node.js v11 to v11.7.0 with Yarn v1.13.0

---

generate-stackbrew-pr.sh

Git user name was already set to "Travis CI User" with its example email

Fix condition to set auto PR committer/author

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.8.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.8.0

Update node.js v11.x from v11.7.0 to v11.8.0

---

10/alpine/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v10.15.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.15.1

Update node.js v10 to v10.15.1 with Yarn v1.13.0

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.10.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.10.0
cc #988

Update node.js v11 to v11.10.0, and Alpine to v3.9

---

.travis.yml
travis.yml.template

Ref:
https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing

Enable Travis CI Fast Finishing

---

10/alpine/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

https://github.com/nodejs/node/releases/tag/v10.15.3
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.15.3
Close #999

Update node.js v10 to v10.15.3 and Alpine to v3.9

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.11.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.11.0

Update node.js v11 from 11.10.1 to v11.11.0

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.12.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.12.0

Update node.js v11 to v11.12.0 with Yarn v1.15.2

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.13.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.13.0

Update node.js v11 from 11.12.0 to v11.13.0

---

6/alpine/Dockerfile
6/jessie-slim/Dockerfile
6/jessie/Dockerfile
6/onbuild/Dockerfile
6/stretch-slim/Dockerfile
6/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v6.17.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.17.1

Update node v6 to 6.17.1 w/ Yarn@1.15.2 & Alpine@3.9

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v11.14.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.14.0

Update node.js v11 from 11.13.0 to v11.14.0

---

10/alpine/Dockerfile
11/alpine/Dockerfile
6/alpine/Dockerfile
8/alpine/Dockerfile

Disable `make` verbose mode in Alpine builds

---

8/alpine/Dockerfile
8/jessie-slim/Dockerfile
8/jessie/Dockerfile
8/onbuild/Dockerfile
8/stretch-slim/Dockerfile
8/stretch/Dockerfile

https://nodejs.org/en/blog/release/v8.16.0/

Update node v8 to 8.16.0 w/ Yarn@1.15.2 & Alpine@3.9

---

.travis.yml
12/alpine/Dockerfile
12/architectures
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v12.0.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.0.0

Add node.js v12.0.0 with Yarn v1.15.2

---

12/alpine/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.1.0/
- https://github.com/nodejs/node/releases/tag/v12.1.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.1.0

Update node.js v12.0.0 to v12.1.0

---

11/alpine/Dockerfile
11/stretch-slim/Dockerfile
11/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v11.15.0/
- https://github.com/nodejs/node/releases/tag/v11.15.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.15.0

Update node.js v11 from v11.14.0 to v11.15.0

---

12/alpine/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.2.0/
- https://github.com/nodejs/node/releases/tag/v12.2.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.2.0

Update node.js v12.1.0 to v12.2.0

---

12/alpine/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.3.1
- https://github.com/nodejs/node/releases/tag/v12.3.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.3.1

Update node.js v12.3.0 to v12.3.1

---

10/alpine/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v10.16.0/
- https://github.com/nodejs/node/releases/tag/v10.16.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.16.0
cc #1044

Update node.js v10 to v10.16.0 with Yarn v1.16.0

---

12/alpine/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.4.0/
- https://github.com/nodejs/node/releases/tag/v12.4.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.4.0

Update node.js v12 from v12.3.1 to v12.4.0

---

12/alpine/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.5.0/
- https://github.com/nodejs/node/releases/tag/v12.5.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.5.0

Update node.js v12 from v12.4.0 to v12.5.0

---

12/alpine/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.6.0/
- https://github.com/nodejs/node/releases/tag/v12.6.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.6.0

Update node.js v12 from v12.5.0 to v12.6.0

---

10/alpine/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v10.16.1/
- https://github.com/nodejs/node/releases/tag/v10.16.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.16.1

Update node.js v10 to v10.16.1 with Yarn v1.17.3

---

10/alpine/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile
12/alpine/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
8/alpine/Dockerfile
8/buster-slim/Dockerfile
8/buster/Dockerfile
8/jessie-slim/Dockerfile
8/jessie/Dockerfile
8/onbuild/Dockerfile
8/stretch-slim/Dockerfile
8/stretch/Dockerfile

WIP - waiting on 8 and 10 sec releases, which will take another ~4 hours to build/release.

Update Node.js 8, 10, 12 for security releases

---

10/architectures
12/architectures
8/architectures

Add arm32v7 to Alpine variants

---

12/alpine/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.9.0/
- https://github.com/nodejs/node/releases/tag/v12.9.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.9.0

Update node.js v12 from v12.8.1 to v12.9.0

---

12/alpine/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.9.1/
- https://github.com/nodejs/node/releases/tag/v12.9.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.9.1

Update node.js v12 from v12.9.0 to v12.9.1

---

12/alpine/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.10.0/
- https://github.com/nodejs/node/releases/tag/v12.10.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.10.0

Update node.js v12 from v12.9.1 to v12.10.0

---

12/alpine/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.11.1/
- https://github.com/nodejs/node/releases/tag/v12.11.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.11.1

Update node.js v12 to v12.11.1 with Yarn v1.19.0

---

8/alpine/Dockerfile
8/buster-slim/Dockerfile
8/buster/Dockerfile
8/jessie-slim/Dockerfile
8/jessie/Dockerfile
8/onbuild/Dockerfile
8/stretch-slim/Dockerfile
8/stretch/Dockerfile

https://nodejs.org/en/blog/release/v8.16.2/

feat: update for Node 8.16.2

---

docs/BestPractices.md

Update Upgrading/downgrading Yarn best practice

---

12/alpine/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.13.0/
- https://github.com/nodejs/node/releases/tag/v12.13.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.13.0

Update node.js v12 from v12.12.0 to v12.13.0

---

generate-stackbrew-library.sh

- https://nodejs.org/en/blog/release/v12.13.0/

feat: add Erbium tag to 12.x, reassign lts tag from 10.x to 12.x

---

10/alpine/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v10.17.0/
- https://github.com/nodejs/node/releases/tag/v10.17.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.17.0

Update node.js v10 to v10.17.0 with Yarn v1.19.1

---

13/alpine/Dockerfile
13/buster-slim/Dockerfile
13/buster/Dockerfile
13/stretch-slim/Dockerfile
13/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v13.0.1

Update node.js v13 from 13.0.0 to 13.0.1

---

13/alpine/Dockerfile
13/buster-slim/Dockerfile
13/buster/Dockerfile
13/stretch-slim/Dockerfile
13/stretch/Dockerfile

https://nodejs.org/en/blog/release/v13.1.0/

Update node.js v13 from 13.0.1 to 13.1.0

---

12/alpine3.10/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.13.1/
- https://github.com/nodejs/node/releases/tag/v12.13.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.13.1

Update node.js v12 from v12.13.0 to v12.13.1

---

13/alpine3.10/Dockerfile
13/buster-slim/Dockerfile
13/buster/Dockerfile
13/stretch-slim/Dockerfile
13/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v13.2.0/
- https://github.com/nodejs/node/releases/tag/v13.2.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.2.0

Update node.js v13 from v13.1.0 to v13.2.0

---

13/alpine3.10/Dockerfile
13/buster-slim/Dockerfile
13/buster/Dockerfile
13/stretch-slim/Dockerfile
13/stretch/Dockerfile

https://nodejs.org/en/blog/release/v13.5.0/

Update node.js v13 to v13.5.0

---

.travis.yml
10/alpine3.11/Dockerfile
10/alpine3.11/docker-entrypoint.sh
10/architectures
12/alpine3.11/Dockerfile
12/alpine3.11/docker-entrypoint.sh
12/architectures
13/alpine3.11/Dockerfile
13/alpine3.11/docker-entrypoint.sh
13/architectures
8/alpine3.11/Dockerfile
8/alpine3.11/docker-entrypoint.sh
8/architectures
architectures
config

Alpine v3.11.0 released
https://alpinelinux.org/posts/Alpine-3.11.0-released.html

Add image for Alpine Linux v3.11

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/alpine3.9/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

Ref https://nodejs.org/en/blog/release/v10.18.1/

feat: Update to 10.18.1

---

update.sh

Reverts nodejs/docker-node#1161

Revert "Fix update.sh invocation with unknown variant"

---

CONTRIBUTING.md

See #1190 for additional context.

Add instructions for submitting a version update PR

---

13/alpine3.10/Dockerfile
13/alpine3.11/Dockerfile
13/buster-slim/Dockerfile
13/buster/Dockerfile
13/stretch-slim/Dockerfile
13/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v13.7.0/
- https://github.com/nodejs/node/releases/tag/v13.7.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.7.0

Update node.js v13.x from 13.6.0 to 13.7.0

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

No blog post yet but there's https://github.com/nodejs/node/releases/tag/v12.16.0.
~Will need to wait for the alpine images regardless~

chore: update to node 12.16 and yarn 1.22

---

test-build.sh

fix: Remove default variant test

---

13/alpine3.10/Dockerfile
13/alpine3.11/Dockerfile
13/buster-slim/Dockerfile
13/buster/Dockerfile
13/stretch-slim/Dockerfile
13/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v13.11.0/
- https://github.com/nodejs/node/releases/tag/v13.11.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.11.0

Update node.js v13 to 13.11.0 with Yarn v1.22.4

---

13/alpine3.10/Dockerfile
13/alpine3.11/Dockerfile
13/buster-slim/Dockerfile
13/buster/Dockerfile
13/stretch-slim/Dockerfile
13/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v13.12.0/
- https://github.com/nodejs/node/releases/tag/v13.12.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.12.0

Update node.js v13 from 13.11.0 to 13.12.0

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/alpine3.9/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v10.20.0/
- https://github.com/nodejs/node/releases/tag/v10.20.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.20.0

Update node.js v10 to v10.20.0 with Yarn v1.22.4

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v12.16.2/
- https://github.com/nodejs/node/releases/tag/v12.16.2
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.16.2

feat: Update to Node 12.16.2 and Yarn 1.22.4

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/alpine3.9/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v10.20.1/
- https://github.com/nodejs/node/releases/tag/v10.20.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.20.1

Update node.js v10 from v10.20.0 to v10.20.1

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v12.16.3
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.16.3

Update node.js v12 from v12.16.2 to v12.16.3

---

14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v14.2.0/
- https://github.com/nodejs/node/releases/tag/v14.2.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.2.0

Update node.js v14 from 14.1.0 to 14.2.0

---

14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v14.3.0/
- https://github.com/nodejs/node/releases/tag/v14.3.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.3.0

Update node.js v14 from 14.2.0 to 14.3.0

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

https://nodejs.org/en/blog/release/v12.17.0/

Update from 12.16.3 to 12.17.0

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/alpine3.9/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile
12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

Fixes #1266 with the 3 security releases today

feat: Update to v10.21.0, v12.18.0, and v14.4.0

---

.travis.yml
12/alpine3.12/Dockerfile
12/alpine3.12/docker-entrypoint.sh
12/architectures
14/alpine3.12/Dockerfile
14/alpine3.12/docker-entrypoint.sh
14/architectures
architectures

Added configuration files to support new version of Alpine linux base image.
Fixes #1274

Added support for Alpine 3.12

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

https://nodejs.org/en/blog/release/v12.18.1/

fix: update to node 12.18.1

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

- https://github.com/nodejs/node/releases/tag/v12.18.2
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.18.2

Update node.js v12 from v12.18.1 to v12.18.2

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/alpine3.9/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/jessie-slim/Dockerfile
10/jessie/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v10.22.0/
- https://github.com/nodejs/node/releases/tag/v10.22.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.22.0

Update node.js v10 from v10.21.0 to v10.22.0

---

14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

- https://nodejs.org/en/blog/release/v14.10.1/
- https://github.com/nodejs/node/releases/tag/v14.10.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.10.1

Update node.js v14 from 14.10.0 to 14.10.1

---

.github/workflows/official-pr.yml

See https://github.community/t/github-actions-are-severely-limited-on-prs/18179/2
See comments in #1348

ci(pr): fix auto-pr using non-current commit

---

10/architectures
12/architectures
14/architectures

This exists mainly to trigger the official-pr action

refactor(architectures): sort and align

---

.github/workflows/official-pr.yml

https://github.com/nodejs/docker-node/pull/1355#issuecomment-704700499

refactor(pr): trigger on pr action change

---

.github/workflows/official-pr.yml

https://github.com/nodejs/docker-node/pull/1355#issuecomment-704698746
Merge after #1355

ci(pr): checkout base_ref

---

.github/workflows/official-pr.yml

https://github.com/crazy-max/ghaction-dump-context
This might aid in seeing what the values of the variables are for the runs.
Refs: #1360

ci(pr): add context dump for debug purposes

---

14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

https://github.com/nodejs/node/releases/tag/v14.13.1

feat: upgrade node to 14.13.1

---

.github/workflows/official-pr.yml

Needs to land before #1373 so the new PR will open in official-images for that change

chore: Trigger upstream PR on config change

---

docs/BestPractices.md

Add control statements and re-run generation

fix: DocToc in Bestpractices.md

---

GOVERNANCE.md

Copied from https://github.com/nodejs/snap/blob/master/CODE_OF_CONDUCT.md

chore: Point to nodejs admin CoC

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

https://nodejs.org/en/blog/release/v15.1.0/

feat: update to node 15.1.0

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/alpine3.9/Dockerfile
14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile

Fixes #1396 since the Debian updates are already merged

feat: November 16 Security Updates for Apline

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

Update node.js v15 from v15.3.0 to v15.4.0
- https://nodejs.org/en/blog/release/v15.4.0/
- https://github.com/nodejs/node/releases/tag/v15.4.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#15.4.0

Update node.js v15 from v15.3.0 to v15.4.0

---

.github/workflows/official-pr.yml
README.md

Removing myself as a Working Group member.
I haven't had time to contribute for some time. I may still do so in the future, but it will be as a regular contributor.

Remove Peter Petrov from Working Group

---

14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

Update node.js v14 from 14.15.1 to 14.15.2
- https://nodejs.org/en/blog/release/v14.15.2/
- https://github.com/nodejs/node/releases/tag/v14.15.2
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.15.2

Update node.js v14 from 14.15.1 to 14.15.2

---

14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

https://nodejs.org/en/blog/release/v14.15.3/

chore: update to 14.15.3

---

README.md

As the title suggests, please add buster and stretch in the image variants list.

Add buster and stretch to the image variant list

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

Update node.js v15 from v15.4.0 to v15.5.0
Reference:
- https://nodejs.org/en/blog/release/v15.5.0/
- https://github.com/nodejs/node/releases/tag/v15.5.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#15.5.0

Update node.js v15 from v15.4.0 to v15.5.0

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/alpine3.9/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile
12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/alpine3.9/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

Fixes #1417 now that all the Alpine releases are out
Fixes #1409

fix: January 2021 Node 10, 12, 14, 15 release

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile
15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

feat: Node v10.23.2 and v15.7.0

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

feat: Node v15.8.0

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/alpine3.13/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

feat: Update to Node 15.9.0

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile
12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/alpine3.13/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

[security]: Node.js February 23 release for v10-15

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/alpine3.13/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

feat: Node.js 15.11.0

---

CONTRIBUTING.md
README.md
generate-stackbrew-library.sh

chore: Update master -> main

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/alpine3.13/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

Update node.js v15 from v15.11.0 to v15.12.0
Reference:
- https://nodejs.org/en/blog/release/v15.12.0/
- https://github.com/nodejs/node/releases/tag/v15.12.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#15.12.0

Update node.js v15 from v15.11.0 to v15.12.0

---

12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

Update node.js v12 from v12.21.0 to v12.22.0
Reference:
- https://nodejs.org/en/blog/release/v12.22.0/
- https://github.com/nodejs/node/releases/tag/v12.22.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.22.0

Update node.js v12 from v12.21.0 to v12.22.0

---

15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/alpine3.13/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

feat: Node 15.13.0

---

10/alpine3.10/Dockerfile
10/alpine3.11/Dockerfile
10/buster-slim/Dockerfile
10/buster/Dockerfile
10/stretch-slim/Dockerfile
10/stretch/Dockerfile
12/alpine3.10/Dockerfile
12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.10/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
15/alpine3.10/Dockerfile
15/alpine3.11/Dockerfile
15/alpine3.12/Dockerfile
15/alpine3.13/Dockerfile
15/buster-slim/Dockerfile
15/buster/Dockerfile
15/stretch-slim/Dockerfile
15/stretch/Dockerfile

[Security]: Node.js April 2021 patch

---

generate-stackbrew-library.sh

fix: Add 16 to stackbrew

---

.github/workflows/official-pr.yml

The `config` file isn't used for the official images/stackbrew anymore, but this is more to retrigger the CI

chore: Update official images workflow

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

feat: Node 16.1.0

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

Update node.js v16 from 16.1.0 to 16.2.0
Reference:
- https://nodejs.org/en/blog/release/v16.2.0/
- https://github.com/nodejs/node/releases/tag/v16.2.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.2.0

Update node.js v16 from 16.1.0 to 16.2.0

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

Update node.js v16 from 16.2.0 to 16.3.0
Reference:
* https://nodejs.org/en/blog/release/v16.3.0/
* https://github.com/nodejs/node/releases/tag/v16.3.0
* https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.3.0

Update node.js v16 from 16.2.0 to 16.3.0

---

14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

chore: update to node 14.17.1

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

Update node.js v16 from 16.3.0 to 16.4.0
Reference:
- https://nodejs.org/en/blog/release/v16.4.0/
- https://github.com/nodejs/node/releases/tag/v16.4.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.4.0
:warning:  The checksum are empty in the new Dockerfiles due to missing files in https://unofficial-builds.nodejs.org/download/release/v16.4.0/  The seams to have stopped while it was running https://unofficial-builds.nodejs.org/logs/202106231214-v16.4.0/build.log

Update node.js v16 from 16.3.0 to 16.4.0

---

12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

feat: July 2021 Security 12, 14, 16 releases

---

12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

These releases just contain a fix for the Windows installer, so doesn't really affect these images. Just to tag for completness

chore: July Security Windows Installer fix

---

14/alpine3.14/Dockerfile
14/alpine3.14/docker-entrypoint.sh
16/alpine3.14/Dockerfile
16/alpine3.14/docker-entrypoint.sh
architectures
versions.json

Alpine just released its v3.14 version.
Closes #1496.
For more information, see release blog post: https://alpinelinux.org/posts/Alpine-3.14.0-released.html
N/A
N/A

Added Alpine 3.14

---

12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/alpine3.13/Dockerfile
12/alpine3.14/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/alpine3.14/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

feat: Second July Node security release

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

feat: Node 16.6.1

---

12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/alpine3.13/Dockerfile
12/alpine3.14/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/alpine3.14/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

feat: Node.js August 2021 security  release

---

12/bullseye-slim/Dockerfile
12/bullseye-slim/docker-entrypoint.sh
12/bullseye/Dockerfile
12/bullseye/docker-entrypoint.sh
14/bullseye-slim/Dockerfile
14/bullseye-slim/docker-entrypoint.sh
14/bullseye/Dockerfile
14/bullseye/docker-entrypoint.sh
16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/bullseye-slim/Dockerfile
16/bullseye-slim/docker-entrypoint.sh
16/bullseye/Dockerfile
16/bullseye/docker-entrypoint.sh
SECURITY.md
architectures
config
versions.json

feat: Add Debian Bullseye images

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/bullseye-slim/Dockerfile
16/bullseye/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

chore: update to 16.7.0

---

12/alpine3.11/Dockerfile
12/alpine3.12/Dockerfile
12/alpine3.13/Dockerfile
12/alpine3.14/Dockerfile
12/bullseye-slim/Dockerfile
12/bullseye/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile
14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/alpine3.14/Dockerfile
14/bullseye-slim/Dockerfile
14/bullseye/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

feat: Node.js August 2021 security release

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/bullseye-slim/Dockerfile
16/bullseye/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

https://nodejs.org/en/blog/release/v16.9.1/

chore: update to v16.9.1

---

16/alpine3.11/Dockerfile
16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/bullseye-slim/Dockerfile
16/bullseye/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

Update node.js v16 from 16.9.1 to 16.10.0 
- https://nodejs.org/en/blog/release/v16.10.0/
- https://github.com/nodejs/node/releases/tag/v16.10.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.10.0

Update node.js v16 from 16.9.1 to 16.10.0

---

14/alpine3.11/Dockerfile
14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/alpine3.14/Dockerfile
14/bullseye-slim/Dockerfile
14/bullseye/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

Update node.js v14 from 14.17.6 to 14.18.0
Reference:
- https://nodejs.org/en/blog/release/v14.18.0/
- https://github.com/nodejs/node/releases/tag/v14.18.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.18.0

Update node.js v14 from 14.17.6 to 14.18.0

---

docs/BestPractices.md

Our images already use this version for new images, and the plain `python` appears to be incorrect from an unrelated issue

docs: Update instructions for python 3

---

14/alpine3.12/Dockerfile
14/alpine3.13/Dockerfile
14/alpine3.14/Dockerfile
14/bullseye-slim/Dockerfile
14/bullseye/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile
17/alpine3.12/Dockerfile
17/alpine3.13/Dockerfile
17/alpine3.14/Dockerfile
17/bullseye-slim/Dockerfile
17/bullseye/Dockerfile
17/buster-slim/Dockerfile
17/buster/Dockerfile
17/stretch-slim/Dockerfile
17/stretch/Dockerfile

feat: NodeJS 14.18.2 and 17.2.0

---

16/alpine3.12/Dockerfile
16/alpine3.13/Dockerfile
16/alpine3.14/Dockerfile
16/bullseye-slim/Dockerfile
16/bullseye/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

feat: NodeJS 16.13.1

---

12/alpine3.12/Dockerfile
12/alpine3.13/Dockerfile
12/alpine3.14/Dockerfile
12/bullseye-slim/Dockerfile
12/bullseye/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

feat: NodeJS 12.22.8

---

17/alpine3.12/Dockerfile
17/alpine3.13/Dockerfile
17/alpine3.14/Dockerfile
17/bullseye-slim/Dockerfile
17/bullseye/Dockerfile
17/buster-slim/Dockerfile
17/buster/Dockerfile
17/stretch-slim/Dockerfile
17/stretch/Dockerfile

feat: NodeJS 17.3.0

---

docs/BestPractices.md

Link to PoLP to clarify why root should be avoided in a container
Provide additional clarity on the reason being inside a container doesn't change best practices.
There are a generation of developers who have only worked in containers and might not be familiar with these principles and security best practices.

docs: Update BestPractices.md: Clarify why running as root is bad mmmmkay

---

17/alpine3.14/Dockerfile
17/alpine3.15/Dockerfile
17/bullseye-slim/Dockerfile
17/bullseye/Dockerfile
17/buster-slim/Dockerfile
17/buster/Dockerfile
17/stretch-slim/Dockerfile
17/stretch/Dockerfile

feat: Node.js 17.4.0

---

12/alpine3.14/Dockerfile
12/alpine3.15/Dockerfile
12/bullseye-slim/Dockerfile
12/bullseye/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

Update node.js v12 from v12.22.9 to v12.22.10
Reference:
- https://nodejs.org/en/blog/release/v12.22.10/
- https://github.com/nodejs/node/releases/tag/v12.22.10
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.22.10

Update node.js v12 from v12.22.9 to v12.22.10

---

16/alpine3.14/Dockerfile
16/alpine3.15/Dockerfile
16/bullseye-slim/Dockerfile
16/bullseye/Dockerfile
16/buster-slim/Dockerfile
16/buster/Dockerfile
16/stretch-slim/Dockerfile
16/stretch/Dockerfile

https://nodejs.org/en/blog/release/v16.14.0/

chore: update to v16.14.0

---

17/alpine3.14/Dockerfile
17/alpine3.15/Dockerfile
17/bullseye-slim/Dockerfile
17/bullseye/Dockerfile
17/buster-slim/Dockerfile
17/buster/Dockerfile
17/stretch-slim/Dockerfile
17/stretch/Dockerfile

https://nodejs.org/en/blog/release/v17.5.0/
`fetch`!!

chore: update to 17.5.0

---

17/alpine3.14/Dockerfile
17/alpine3.15/Dockerfile
17/bullseye-slim/Dockerfile
17/bullseye/Dockerfile
17/buster-slim/Dockerfile
17/buster/Dockerfile
17/stretch-slim/Dockerfile
17/stretch/Dockerfile

https://nodejs.org/en/blog/release/v17.6.0/

chore: update to 17.6.0

---

17/alpine3.14/Dockerfile
17/alpine3.15/Dockerfile
17/bullseye-slim/Dockerfile
17/bullseye/Dockerfile
17/buster-slim/Dockerfile
17/buster/Dockerfile
17/stretch-slim/Dockerfile
17/stretch/Dockerfile

feat: NodeJS 17.7.1

---

.github/workflows/automatic-updates.yml
build-automation.mjs

https://github.com/actions/github-script/blob/main/README.md#reading-step-results

chore: use default output from action rather than manual output

---

README.md

node version update

---

.github/workflows/automatic-updates.yml
build-automation.mjs

Job is currently failing due to
```
The workflow is not valid. .github/workflows/automatic-updates.yml (Line: 30, Col: 27): Unexpected symbol: '('. Located at position 47 within expression: steps.updt.outputs.result.updatedVersions.join(', ') .github/workflows/automatic-updates.yml (Line: 31, Col: 18): Unexpected symbol: '('. Located at position 47 within expression: steps.updt.outputs.result.updatedVersions.join(', ')
```

fix: avoid function calls in GH action script

---

.github/workflows/automatic-updates.yml

chore: update formatting of commit message as well

---

17/alpine3.14/Dockerfile
17/alpine3.15/Dockerfile
17/bullseye-slim/Dockerfile
17/bullseye/Dockerfile
17/buster-slim/Dockerfile
17/buster/Dockerfile
17/stretch-slim/Dockerfile
17/stretch/Dockerfile

feat: Node.js 17.8.0

---

.github/workflows/automatic-updates.yml

Hopefully, this sets the correct author and also has the correct permissions to trigger CI and request a review

chore: use PAT for automated pull request

---

update.sh

Ref https://github.com/nodejs/docker-node/pull/1688#pullrequestreview-931863678
Note that `./update.sh 14` is broken, it still updates all files. Not sure when or how it broke (we should rewrite these scripts to be node scripts 😅 EDIT: hah: #1368)

fix: only update yarn if there are other changes to the dockerfile

---

12/alpine3.14/Dockerfile
12/alpine3.15/Dockerfile
12/bullseye-slim/Dockerfile
12/bullseye/Dockerfile
12/buster-slim/Dockerfile
12/buster/Dockerfile
12/stretch-slim/Dockerfile
12/stretch/Dockerfile

feat: Node.js 12.22.12

---

14/alpine3.14/Dockerfile
14/alpine3.15/Dockerfile
14/bullseye-slim/Dockerfile
14/bullseye/Dockerfile
14/buster-slim/Dockerfile
14/buster/Dockerfile
14/stretch-slim/Dockerfile
14/stretch/Dockerfile

Manual PR since the bot is currently picking up the other key changes in other versions

feat: Node.js 14.9.2

---

README.md

fixes #1657
https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
> Mount host paths or named volumes, specified as sub-options to a service.

docs: clarify docker compose volume explanation

---

.github/workflows/markdown-link-check.yml

Fix GitHub Action for markdown-link-check trigger
Something wrong in #1742, thanks for catching-up from @nschonni

Fix GitHub Action for markdown-link-check trigger

---

19/alpine3.15/Dockerfile
19/alpine3.15/docker-entrypoint.sh
19/alpine3.16/Dockerfile
19/alpine3.16/docker-entrypoint.sh
19/bullseye-slim/Dockerfile
19/bullseye-slim/docker-entrypoint.sh
19/bullseye/Dockerfile
19/bullseye/docker-entrypoint.sh
19/buster-slim/Dockerfile
19/buster-slim/docker-entrypoint.sh
19/buster/Dockerfile
19/buster/docker-entrypoint.sh
versions.json

feat: Node.js 19.0.0

---

18/alpine3.15/Dockerfile
18/alpine3.16/Dockerfile
18/bullseye-slim/Dockerfile
18/bullseye/Dockerfile
18/buster-slim/Dockerfile
18/buster/Dockerfile
versions.json

Added the new "Hydrogen" code name for the new LTS

fix: Node.js 18.12.0 - Hydrogen LTS

---

.github/workflows/automatic-updates.yml

As discussed in https://github.com/nodejs/docker-node/pull/1850#discussion_r1110350056, trying an alternate to try and address the error mentioned in the PR description

ci: Remove At sign from team mention config

---

.github/workflows/build-test.yml

Close: https://github.com/nodejs/docker-node/issues/1847
I replaced [lots0logs/gh-action-get-changed-files](https://github.com/lots0logs/gh-action-get-changed-files) to [tj-actions/changed-files](https://github.com/tj-actions/changed-files).
`lots0logs/gh-action-get-changed-files` is no longer maintained. So use the similar GitHub Actions, `tj-actions/changed-files`.

replace gh-action-get-changed-files

---

docs/BestPractices.md

Make example `docker run` command follow best practice described in section `## Handling Kernel Signals`
Examples should follow best practices :)
Makes the documentation less ambiguous.

Add `--init` to `docker run` example

---

19/alpine3.16/Dockerfile
19/alpine3.17/Dockerfile
19/bullseye-slim/Dockerfile
19/bullseye/Dockerfile
19/buster-slim/Dockerfile
19/buster/Dockerfile

Fixes #1875 without v14 key changes

feat: Node.js 19.9.0

---

18/alpine3.16/Dockerfile
18/alpine3.17/Dockerfile
18/bullseye-slim/Dockerfile
18/bullseye/Dockerfile
18/buster-slim/Dockerfile
18/buster/Dockerfile

Fixes #1878 without the v14 changes

feat: Node.js 18.16.0

---

20/alpine3.16/Dockerfile
20/alpine3.16/docker-entrypoint.sh
20/alpine3.17/Dockerfile
20/alpine3.17/docker-entrypoint.sh
20/bullseye-slim/Dockerfile
20/bullseye-slim/docker-entrypoint.sh
20/bullseye/Dockerfile
20/bullseye/docker-entrypoint.sh
20/buster-slim/Dockerfile
20/buster-slim/docker-entrypoint.sh
20/buster/Dockerfile
20/buster/docker-entrypoint.sh
versions.json

feat: Node.js 20.0.0

---

.github/PULL_REQUEST_TEMPLATE.md

Fix a typo in the PR template and slightly reword it to improve readability

Adjust typo in PR template

---

20/alpine3.17/Dockerfile
20/alpine3.18/Dockerfile
20/bookworm-slim/Dockerfile
20/bookworm/Dockerfile
20/bullseye-slim/Dockerfile
20/bullseye/Dockerfile
20/buster-slim/Dockerfile
20/buster/Dockerfile

Manual PR for unrelated key changes.
Closes #1957

feat: Node.js 20.6.0

---

20/alpine3.17/Dockerfile
20/alpine3.18/Dockerfile
20/bookworm-slim/Dockerfile
20/bookworm/Dockerfile
20/bullseye-slim/Dockerfile
20/bullseye/Dockerfile
20/buster-slim/Dockerfile
20/buster/Dockerfile

feat: Node.js 20.6.1

---

README.md
docs/BestPractices.md

Only changes the documentation...

Add an example of how to create smaller images without npm/yarn

---

versions.json

20 is now has the codename Iron, so that should be included as a new tag

feat: Nodejs 20 LTS Iron codename

---

18/alpine3.19/Dockerfile
18/alpine3.20/Dockerfile
20/alpine3.19/Dockerfile
20/alpine3.20/Dockerfile
21/alpine3.19/Dockerfile
21/alpine3.20/Dockerfile
22/alpine3.19/Dockerfile
22/alpine3.20/Dockerfile
Dockerfile-alpine.template

Installs `setuptool` to fix the error in ther configure script about missing `distutils`
Fixes #2096

Fix version 18 on arm64v8 arch

---

docs/BestPractices.md

Technically, this is only needed for Node 18 on Alpine 3.20 but since it's part of the virtual group and gets deleted, this is the simplest without overcomplicating the docs.

Update the node-gyp alpine docs section to account for Node 18 in Alpine 3.20 python issue

---

23/alpine3.19/Dockerfile
23/alpine3.19/docker-entrypoint.sh
23/alpine3.20/Dockerfile
23/alpine3.20/docker-entrypoint.sh
23/bookworm-slim/Dockerfile
23/bookworm-slim/docker-entrypoint.sh
23/bookworm/Dockerfile
23/bookworm/docker-entrypoint.sh
23/bullseye-slim/Dockerfile
23/bullseye-slim/docker-entrypoint.sh
23/bullseye/Dockerfile
23/bullseye/docker-entrypoint.sh
versions.json

Adds the v23 major line. Modelled after #2071 and #1980.
See also https://nodejs.org/en/blog/release/v23.0.0.

feat: Node.js 23.0.0

---

22/alpine3.19/Dockerfile
22/alpine3.20/Dockerfile
22/bookworm-slim/Dockerfile
22/bookworm/Dockerfile
22/bullseye-slim/Dockerfile
22/bullseye/Dockerfile

Manual 22 version update.
Closes #2150

feat: Node.js 22.10.0

---

23/alpine3.19/Dockerfile
23/alpine3.20/Dockerfile
23/bookworm-slim/Dockerfile
23/bookworm/Dockerfile
23/bullseye-slim/Dockerfile
23/bullseye/Dockerfile

feat: Node.js 23.1.0

---

18/alpine3.19/Dockerfile
18/alpine3.20/Dockerfile
18/bookworm-slim/Dockerfile
18/bookworm/Dockerfile
18/bullseye-slim/Dockerfile
18/bullseye/Dockerfile
23/alpine3.19/Dockerfile
23/alpine3.20/Dockerfile
23/bookworm-slim/Dockerfile
23/bookworm/Dockerfile
23/bullseye-slim/Dockerfile
23/bullseye/Dockerfile

Manual PR to skip unrelated v20 key changes.
Closes #2161

feat: Node.js 18.20.5 and 23.2.0

---

.github/workflows/scorecard.yml

Recommendation from https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions
Related to #2208

ci: add OSSF scanning
