0.10/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile, 0.8/Dockerfile, 0.8/slim/Dockerfile, 0.8/wheezy/Dockerfile
For the slim variant, we also need to temporarily install
ca-certificates to make this work.
=> Download node binary and SHASUMs via HTTPS. Fixes #23

0.10/Dockerfile, 0.10/onbuild/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/onbuild/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile
Test build looks good:
```
[christopher@JoyentMacBookPro ~/GitHub/docker-node]$ ./test-build.sh 
Building 0.10.40...
Sending build context to Docker daemon 8.704 kB
Sending build context to Docker daemon 
Step 0 : FROM buildpack-deps:jessie
---> 4b708e6c0f6c
Step 1 : RUN gpg --keyserver pool.sks-keyservers.net --recv-keys 7937DFD2AB06298B2293C3187D33FF9D0246406D 114F43EE0176B71C7BC219DD50A3051F888C628D
---> Using cache
---> 9d3a855fe348
Step 2 : ENV NODE_VERSION 0.10.40
---> Using cache
---> 206e81a33d36
Step 3 : ENV NPM_VERSION 2.11.3
---> Using cache
---> 9eb2c443f777
Step 4 : RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" 	&& curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" 	&& gpg --verify SHASUMS256.txt.asc 	&& grep " …
```
=> 0.10.40 0.12.7

0.10/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile, 0.8/Dockerfile, 0.8/slim/Dockerfile, 0.8/wheezy/Dockerfile
When "gpg" is given multiple keys, it will only exit non-zero if _all_ the keys fail to download, so sometimes we'll get this line succeeding, but a transient failure (network, keyserver, or otherwise) can cause us to get a false positive and a build that fails later at verifying binaries.
See also https://github.com/docker-library/php/pull/92 (and all the other PRs linked into that one).
(and the main reason I've made the PR is because the official build server actually ran into this scenario :disappointed: :innocent:)
=> Update "gpg" usage to be more resilient to transient failure

generate-stackbrew-library.sh
This updates the generate-stackbrew-library.sh script to reflect the recent org change to nodejs. Once this lands I'll proceed with the pull request to https://github.com/docker-library/official-images to get things updated.
cc @nodejs/docker
=> Update stackbrew for nodejs org change

4.0/Dockerfile, 4.0/onbuild/Dockerfile, 4.0/slim/Dockerfile, 4.0/wheezy/Dockerfile, generate-stackbrew-library.sh
This adds Node.js v4.0.0 and sets it as the "latest" image.
Things to note:
- The slim variant is based on iojs version of slim which is based off buildpack-deps:jessie-curl. This seemed a cleaner way to go rather than the fancy footwork approach of install/uninstalling curl and ca-certificates that was done in the slim variants of 0.10 and 0.12.
- I'm including a wheezy variant similar to the Node.js 0.10 and 0.12 to keep things consistent.
- generate-stackbrew-library.sh has been updated to set "latest" to 4.0
- https://github.com/nodejs/docker-node/pull/41 will need to be merged first to avoid conflicts
Test build via test-build.sh passes :)
Closes #39
cc @nodejs/docker
=> Node 4.0.0

4.2/Dockerfile, 4.2/onbuild/Dockerfile, 4.2/slim/Dockerfile, 4.2/wheezy/Dockerfile
Update Node.js to v4.2.1 ('Argon' (LTS) Release)
Related: nodejs/node#3337
=> Update to 4.2.1

README.md
It's a minor update but the command will not work without giving it a path (`.` in this case).
=> Fix typo in README's docker build command.

5.2/Dockerfile, 5.2/onbuild/Dockerfile, 5.2/slim/Dockerfile, 5.2/wheezy/Dockerfile, generate-stackbrew-library.sh
Because its new. Assume I screwed this PR up! :)
=> Update Node to 5.2.0

5.3/Dockerfile, 5.3/onbuild/Dockerfile, 5.3/slim/Dockerfile, 5.3/wheezy/Dockerfile
Upgrade Node.js v5 Docker Image to v5.3.0
Related: nodejs/node#4281
=> Update Node to 5.3.0

5.4/Dockerfile, 5.4/onbuild/Dockerfile, 5.4/slim/Dockerfile, 5.4/wheezy/Dockerfile
This PR upgrades Node.js to v5.4.1.
Related: nodejs/node#4626
Signed-off-by: Hans Kristian Flaatten <hans.kristian.flaatten@dnt.no>
=> Upgrade Node to 5.4.1

README.md
This PR updates the following parts of the README from [docker-library/docs](https://github.com/docker-library/docs/blob/master/node/README.md). It may be confusing for users if the docs in this repo and on the official image on Docker Hub are too different.
* Examples where the `onbuild` image variant is used
* Description of the `onbuild` image variant
* Supported Docker versions
=> Update instructions in README for onbuild variant

README.md
This PR documents why the `onbuild` image variant does not install according to npm shrinkwrap. See discussion in #65.
=> Document why onbuild does not install according to shrinkwrap

0.10/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile, 4.3/Dockerfile, 4.3/slim/Dockerfile, 4.3/wheezy/Dockerfile, 5.6/Dockerfile, 5.6/slim/Dockerfile, 5.6/wheezy/Dockerfile
This updates all relevant Dockerfiles to use the xz compressed tarball for node-v$NODE_VERSION-linux-x64.tar.xz.
Note that for the slim variants we need to install and then remove the xz-utils package to make this viable.
I ran a test build via test-build.sh and that was successful, but I'd like for a few people to give this a review just to be safe (cc @nodejs/docker)
=> Switch to xz compression for all images. Fixes #77

5.7/Dockerfile, 5.7/onbuild/Dockerfile, 5.7/slim/Dockerfile, 5.7/wheezy/Dockerfile, generate-stackbrew-library.sh
Per: https://nodejs.org/en/blog/release/v5.7.0/
Test build passes.
Next up: the PR to the official repo
=> Update to v5.7.0. Fixes #105

5.7/Dockerfile, 5.7/onbuild/Dockerfile, 5.7/slim/Dockerfile, 5.7/wheezy/Dockerfile
Per https://github.com/nodejs/node/pull/5464 and https://nodejs.org/en/blog/release/v5.7.1/
=> Update for Node.js 5.7.1

update.sh
We should use the https URL when checking for Node.js updates.
This is just me being fussy :)
=> Use https in update.sh

README.md, docs/BestPractices.md
Addresses https://github.com/nodejs/nodejs.org/issues/432
=> Best Practices Document

generate-stackbrew-library.sh, test-build.sh, update.sh
I added some logic to the maintenance scripts to exclude the new "docs" directory. Previously the scripts treated all directories as if they were "image" versions.
=> Exclude docs directory. Fixes #126

.travis.yml
This enables Travis-CI for a simple test build of the docker-node images. This will streamline image updates a bit as the build test we use (via ./testbuild.sh) will happen automatically for pull requests etc.
We'll need Travis-CI enabled for this GitHub repo as well.
I'll do a follow-up PR to the README.md so it shows the build status :)
=> Enable travis-ci test builds. Closes #13

0.10/slim/Dockerfile, 0.12/slim/Dockerfile
This updates the 0.10 and 0.12 slim variant Dockerfiles to be consistent with the 4.x and 5.x slim variants:
- Base the image off of `buildpack-deps:jessie-curl` instead of debian:jessie
- Only install the xz-utils package
Test build looks good: https://travis-ci.org/chorrell/docker-node/builds/122896535
=> Use buildpack-deps:jessie-curl for 0.10 and 0.12 slim images. See #144

test-build.sh
This allows for easily testing newer variants without having to update
test-build.sh
=> Better variant test

0.10/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile, 4.4/Dockerfile, 4.4/slim/Dockerfile, 4.4/wheezy/Dockerfile, 5.11/Dockerfile, 5.11/slim/Dockerfile, 5.11/wheezy/Dockerfile, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template
Reverts nodejs/docker-node#162
See https://github.com/nodejs/docker-node/pull/162#issuecomment-214859596
=> Revert "Moved the environment variables to the top of the Dockerfile"

README.md
This PR updates the section about the Docker Working Group in the README.md.
=> Add list of working group collaborators to README

generate-stackbrew-library.sh
It should default to v5.11.0. Partially fixes #174.
Once this lands we'll need a PR to the docker hub to get this fixed upstream.
I think we also need to look at the update script and see if we can get some logic added to update generate-stackbrew-library.sh
=> Set correct default version for node:5

0.10/Dockerfile, 0.10/onbuild/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/onbuild/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile, 4.4/Dockerfile, 4.4/onbuild/Dockerfile, 4.4/slim/Dockerfile, 4.4/wheezy/Dockerfile, 5.11/Dockerfile, 5.11/onbuild/Dockerfile, 5.11/slim/Dockerfile, 5.11/wheezy/Dockerfile, 6.1/Dockerfile, 6.1/onbuild/Dockerfile, 6.1/slim/Dockerfile, 6.1/wheezy/Dockerfile, generate-stackbrew-library.sh
Node.js updates for:
- v6.1.0
- v5.11.1
- v4.4.4
- v0.12.14
- v0.10.45
See #177
Closes #178 and closes #179
=> Openssl updates 20160505

6.3/Dockerfile, 6.3/onbuild/Dockerfile, 6.3/slim/Dockerfile, 6.3/wheezy/Dockerfile
Upgrade Node v6 Docker Image to v6.3.0.
Related: nodejs/node#7550, nodejs/node#7441
Signed-off-by: Hans Kristian Flaatten <hans.kristian.flaatten@dnt.no>
=> Upgrade Node to 6.3.0

README.md
Attempts to explain the rationale behind the `NPM_CONFIG_LOGLEVEL`.
Close: nodejs/docker-node#57
Related: nodejs/docker-iojs#36
Signed-off-by: Hans Kristian Flaatten <hans.kristian.flaatten@dnt.no>
=> Explain the npm verbosity in the node image

0.10/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile, 4.5/Dockerfile, 4.5/slim/Dockerfile, 4.5/wheezy/Dockerfile, 5.12/Dockerfile, 5.12/slim/Dockerfile, 5.12/wheezy/Dockerfile, 6.4/Dockerfile, 6.4/slim/Dockerfile, 6.4/wheezy/Dockerfile, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template
This adds compatibility with the Debian/Ubuntu  packages that assume a
'nodejs' binary
This was easy enough to add, but I'd like some review and discussion.
=> Add symlink to nodejs. Fixes #181

Dockerfile-onbuild.template, README.md
It's currently impossible to prevent npm installing devDependencies when using the node onbuild images. Adding a NODE_ENV ARG enables `docker build --build-arg NODE_ENV=production .`, which is the equivalent of `npm install --production`. Providing the `--build-arg` is optional, so this is backwards-compatible.
=> Add NODE_ENV ARG to onbuild template

0.10/onbuild/Dockerfile, 0.12/onbuild/Dockerfile, 4.5/onbuild/Dockerfile, 6.6/onbuild/Dockerfile, Dockerfile-onbuild.template
This ensures that the value of NODE_ENV is made available to the CMD
context. This ensures commands such as `npm start` or `node index.js`
are using the correct NODE_ENV.
See comments in
https://github.com/docker-library/official-images/pull/2156
=> Set ENV for NODE_ENV

generate-stackbrew-library.sh
The new format is based on RFC 2822.
See:
https://github.com/docker-library/official-images#instruction-format
Also, generate-stackbrew-library.sh now no longer hardcodes the variant
names (onbuild slim wheezy)
=> Update to use newer manifest file format

0.10/Dockerfile, 0.10/onbuild/Dockerfile, 0.10/slim/Dockerfile, 0.10/wheezy/Dockerfile, 0.12/Dockerfile, 0.12/onbuild/Dockerfile, 0.12/slim/Dockerfile, 0.12/wheezy/Dockerfile, 4.6/Dockerfile, 4.6/onbuild/Dockerfile, 4.6/slim/Dockerfile, 4.6/wheezy/Dockerfile, 6.7/Dockerfile, 6.7/onbuild/Dockerfile, 6.7/slim/Dockerfile, 6.7/wheezy/Dockerfile, generate-stackbrew-library.sh
This is an update for:
- Node.js v6.7.0
- Node.js v4.6.0
- Node.js v0.12.16
- Node.js v0.10.47
See:
- https://nodejs.org/en/blog/vulnerability/september-2016-security-release
s/
- https://nodejs.org/en/blog/release/v6.7.0/
- https://nodejs.org/en/blog/release/v4.6.0/
- https://nodejs.org/en/blog/release/v0.12.16/
- https://nodejs.org/en/blog/release/v0.10.47/
=> Security updates, September 2016. Closes #235

test-build.sh
This adds some improvements to test-build.sh when dealing with variants and non-docker directories (like docs). This should help with testing #222 and #223
=> Improve test

Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template
Allows running non-root commands (such as npm). Fixes #253
=> Added a non root user

Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template
This is a workaround for docker-machine/boot2docker issue 581, see
https://github.com/boot2docker/boot2docker/issues/581
Although Docker for Mac/Windows doesn't have this issue, there are still many developers using docker-machine with VirtualBox+NFS for performance reasons.
Using a normal user with a home directory instead of a system user faciliates usage of the docker images as e.g. installing packages can simply done in the home directory.
=> Add node group/user with gid/uid 1000 and a home directory

.travis.yml, generate-stackbrew-library.sh
Sets 7.2.0 as the 'latest'
This got missed from the v7.2.0 update
=> Update for v7.2.0

README.md
Fixing a formatting error in the README.md file.
=> Incorrect backtick

docs/BestPractices.md
Seems like a H2 is more suitable than a H4, since Memory has nothing to do with non-root users
=> docs: fix best-practices memory heading level

4.7/onbuild/Dockerfile, 6.9/onbuild/Dockerfile, 7.4/onbuild/Dockerfile, Dockerfile-onbuild.template
Cleaning out the npm modules cache after installing will help keep down the size of images built with the _onbuild_ variant. Follows practices used in other dockerfiles with package-managers.
=> Run 'npm cache clean' after 'npm install' in onbuild variants

4.7/Dockerfile, 4.7/alpine/Dockerfile, 4.7/onbuild/Dockerfile, 4.7/slim/Dockerfile, 4.7/wheezy/Dockerfile, 6.9/Dockerfile, 6.9/alpine/Dockerfile, 6.9/onbuild/Dockerfile, 6.9/slim/Dockerfile, 6.9/wheezy/Dockerfile
See:
- https://nodejs.org/en/blog/release/v4.7.3/
- https://nodejs.org/en/blog/release/v6.9.5/
- https://nodejs.org/en/blog/vulnerability/openssl-january-2017/
- https://github.com/nodejs/docker-node/issues/314
=> Update for Node.js v4.7.3 and v6.9.5

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/wheezy/Dockerfile, 6.10/Dockerfile, 6.10/alpine/Dockerfile, 6.10/slim/Dockerfile, 6.10/wheezy/Dockerfile, 7.6/Dockerfile, 7.6/alpine/Dockerfile, 7.6/slim/Dockerfile, 7.6/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template, update.sh
Disclaimer: This is a **proposal** PR which requires discussion. Please do not merge unless consensus has been established.
This PR adds [Yarn](https://yarnpkg.com/) as an alternative package manager to the existing images. It's added as a separate layer and the size increase is small (up to ~3.5 MB currently; for example the `7.6.0-alpine` tag increases in size from 56.2 MB to 59.7 MB). The `update.sh` script is updated to automatically detect the latest stable Yarn release ~~using the GitHub API~~.
Adding Yarn has been by far the most upvoted request in our issue tracker (#243).
Notes:
* There is a previous PR (#260) which also adds Yarn. The current PR is different in that it doesn't create new tags, instead adding Yarn to the existing ones. Also, the installation method is different …
=> Proposal to add Yarn to the existing images

7.7/Dockerfile, 7.7/alpine/Dockerfile, 7.7/onbuild/Dockerfile, 7.7/slim/Dockerfile, 7.7/wheezy/Dockerfile
https://nodejs.org/en/blog/release/v7.7.1/
=> Update for Node.js v7.7.1

Dockerfile-alpine.template
This will add a group called `node` and a user called `node` to best mimic how [wheezy](https://github.com/nodejs/docker-node/blob/65160d372031e836a412c50f741c13bc838858a5/7.4/wheezy/Dockerfile) adds a group and user.
There doesn't appear to be a long form of the flags (`--`) so I used the short form (`-`).
Below is the full list of flags from `--help`.
```
Usage: addgroup [-g GID] [-S] [USER] GROUP
Add a group or add a user to a group
-g GID  Group id
-S      Create a system group
```
```
Usage: adduser [OPTIONS] USER [GROUP]
Create new user, or add USER to GROUP
-h DIR          Home directory
-g GECOS        GECOS field
-s SHELL        Login shell
-G GRP          Add user to existing group
-S              Create a system user
-D              Don't assign a password
-H              Don't …
```
=> Add group & user in alpine to match wheezy

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/wheezy/Dockerfile, 6.10/Dockerfile, 6.10/alpine/Dockerfile, 6.10/slim/Dockerfile, 6.10/wheezy/Dockerfile, 7.8/Dockerfile, 7.8/alpine/Dockerfile, 7.8/slim/Dockerfile, 7.8/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template
If ha.pool.sks-keyservers.net times out we try pgp.mit.edu then
keyserver.pgp.com.
This should hopefully resolve the occasional build errors we see in
Travis and for issues like #340
=> Try other key servers if ha.pool.sks-keyservers.net is unreachable

docs/BestPractices.md
Since the `node` user was added to the alpine variant, there is no need to recommend that they need to create the `node` user. In fact, it would break. Only the `onbuild` variant does not have the user.
I also added the `USER node` syntax to show how to [set the user](https://docs.docker.com/engine/reference/builder/#user) in the dockerfile.
=> Update BestPractices.md to remove alpine user

7.9/Dockerfile, 7.9/alpine/Dockerfile, 7.9/slim/Dockerfile, 7.9/wheezy/Dockerfile
We only update yarn for branches that have a new release. In this case
v4 and v6
=> Partial revert for #390

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/wheezy/Dockerfile, 6.10/Dockerfile, 6.10/alpine/Dockerfile, 6.10/slim/Dockerfile, 6.10/wheezy/Dockerfile, 7.10/Dockerfile, 7.10/alpine/Dockerfile, 7.10/slim/Dockerfile, 7.10/wheezy/Dockerfile
=> Upgrade to yarn 0.24.4

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/wheezy/Dockerfile, 6.10/Dockerfile, 6.10/alpine/Dockerfile, 6.10/slim/Dockerfile, 6.10/wheezy/Dockerfile, 7.10/Dockerfile, 7.10/alpine/Dockerfile, 7.10/slim/Dockerfile, 7.10/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template, update.sh
This will enabled `curl` to request compressed content and automatically decompress if the content was compressed, which can speed up the build process and save a little bit of bandwidth.
=> Enable curl compressed

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/wheezy/Dockerfile, 6.10/Dockerfile, 6.10/alpine/Dockerfile, 6.10/slim/Dockerfile, 6.10/wheezy/Dockerfile, 7.10/Dockerfile, 7.10/alpine/Dockerfile, 7.10/slim/Dockerfile, 7.10/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template
This PR reorders the keyservers that we attempt to fetch keys from, in order to move `ha.pool.sks-keyservers.net` to the end of the list. While this pool it is supposed to be "HA", it has been unstable for far too long, has been slowing `test-build.sh` drastically, and has been the cause for virtually all Travis build timeouts.
=> Reorder keyservers

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/wheezy/Dockerfile, 6.10/Dockerfile, 6.10/alpine/Dockerfile, 6.10/slim/Dockerfile, 6.10/wheezy/Dockerfile, 7.10/Dockerfile, 7.10/alpine/Dockerfile, 7.10/slim/Dockerfile, 7.10/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template
Resolves #401 
The provided Yarn tarball is now used, instead of the bare webpacked .js file. The tarball is unpacked in `/opt/yarn` and the necessary symlinks are created in `/usr/local/bin`. Installation procedure is the same across all image variants (including Alpine).
Users wishing to upgrade Yarn themselves can easily achieve that by deleting the contents of `/opt/yarn` and unpacking a more recent tarball there.
The size increase is negligible (less than 0.1 MB).
=> Change Yarn installation method to use tarball

docs/BestPractices.md
Looks like the `Non-root User` section of `BestPractices.md` was outdated/incorrect. The `onbuild` image inherits the `node` user from the base one, there shouldn't be anything different about it.
=> Update "Non-root User" docs

.travis.yml, 8.0/Dockerfile, 8.0/alpine/Dockerfile, 8.0/onbuild/Dockerfile, 8.0/slim/Dockerfile, 8.0/wheezy/Dockerfile, generate-stackbrew-library.sh
#410 with node 7 removed. Unsure which of these (if any) you want 😀
=> Add Node.js v8.0.0

8.0/alpine/Dockerfile
Just 8.0, right?
This does _not_ update `Dockerfile-alpine.template`, which means running `update.sh` will rollback the version in this dockerfile. Is that expected/wanted?
=> Upgrade alpine in node@8 to 3.6

README.md
From  [Docker WG Governance Document on Collaborators](https://github.com/nodejs/docker-node/blob/master/GOVERNANCE.md#collaborators):
> Individuals making significant and valuable contributions are made Collaborators and given commit-access to the project. These individuals are identified by the WG and their addition as Collaborators is discussed as a pull request to this project's README.md.
I propose adding Simen Brekkhus (@SimenB) as a _Collaborator_ to the @nodejs/docker team for his contributions to #272 #377 #383 #400 #411 and soon #412 #413.
=> Add Simen Brekkhus (@SimenB) as a collaborator

CONTRIBUTING.md
There has been some confusion recently regarding when/how Yarn versions should be updated. I think we should agree on a specific strategy and document it somewhere. A `CONTRIBUTING.md` file seems like a good place for that, especially given that there is a broken link to it in our `README.md` :smile: 
The current proposal aims to ensure that a new Yarn release does not cause regressions in an already published SemVer-minor image tag. It's partially motivated by previous issues such as #386. It might be updated after Yarn 1.0 is released.
/cc @nodejs/docker @PeterDaveHello @Daniel15 @bestander for comments.
=> Add CONTRIBUTING.md including Yarn version update policy

8.0/onbuild/Dockerfile, Dockerfile-onbuild.template
Fixes #419 properly
Replaces #420 #421 
Only updated the 8.x Dockerfile for now, because the fix only concerns NPM 5. It is backwards-compatible so future updates to older branches won't be an issue.
=> Force cache cleaning

update.sh
Covers the changes in #426 and will prevent it being reverted with future versions.
Also handles that the Alpine image is now 3.6 with 8+
=> Update update.sh for Node 8+ change of Alpine version

.travis.yml, 8.1/Dockerfile, 8.1/alpine/Dockerfile, 8.1/onbuild/Dockerfile, 8.1/slim/Dockerfile, 8.1/wheezy/Dockerfile, generate-stackbrew-library.sh
https://nodejs.org/en/blog/release/v8.1.0/
=> Update to node 8.1.0

CONTRIBUTING.md
Added a section about dependencies since it's one of the most common contribution.
=> Update contributing documentation file

docs/BestPractices.md
see https://docs.docker.com/release-notes/docker-engine/#1130-2017-01-18
=> documentation fix: init flag is included in docker only after 1.13 not 1.3

.travis.yml, 7.10/Dockerfile, 7.10/alpine/Dockerfile, 7.10/onbuild/Dockerfile, 7.10/slim/Dockerfile, 7.10/wheezy/Dockerfile, generate-stackbrew-library.sh
Note that we had to resurrect 7.10/ to include the v7.10.1 security fix.
See:
- https://nodejs.org/en/blog/release/v7.10.1/
- https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
=> Update for Node.js v7.10.1. Fixes #456.

CONTRIBUTING.md
The intention was always to update on SemVer PATCH releases (which makes the most sense), not MINOR. I messed that up in #393, apologies for which.
=> Correct mistaken Yarn update policy.

README.md
It looks like the ONBUILD variant was deprecated in https://github.com/docker-library/official-images/issues/2076
This change adds one line to the README.md file.
=> Update readme to deprecate ONBUILD variable

Dockerfile-slim.template, Dockerfile-wheezy.template, Dockerfile.template, README.md, architectures, functions.sh, generate-stackbrew-library.sh, test-build.sh, update.sh
- Add an architectures file to list supported architectures and
variants.
- Use `dpkg --print-architecture` or `apk --print-arch` in Dockerfile
to get current architecture.
- Add a functions.sh to put utility functions, including
- get_arch: get the current running architecture.
- get_variants: get corresponding supported variants based on the
running architecture.
- Modify update.sh and generate-stackbrew-library.sh to detect
running architecture
Signed-off-by: Yihong Wang <yh.wang@ibm.com>
=> Support Linux on ppc64le

architectures, functions.sh, generate-stackbrew-library.sh, update.sh
Enhance the `generate-stackbrew-library.sh` to generate `Architectures`
information.
Signed-off-by: Yihong Wang <yh.wang@ibm.com>
=> Generate 'Architectures' information

README.md, docs/BestPractices.md
Also highlights the `Best Practices` section in the `README.md` file so
the new instructions are easier to find.
Special thanks to:
* @blueimp for the uid/gid change command
* @LaurentGoderre for the user rename command
Refs #289
=> Adds instructions for modifying the `node` user

README.md
As onbuild is deprecated - update the first Dockerfile example in the README to use node:6 (current LTS) as a base image. In addition this change adds a comment to the Dockerfile how to specify versions.
=> Update Dockerfile example in README

4.8/architectures, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile.template, functions.sh, update.sh
- Support `s390x` in all of the version except 4.8 and the following
variants: default, alpine, stretch, slim and onbuild
- Generate proper `architectures` for the stackbrew
- Update `update.sh` in order to be used on s390x
- `s390` is not supported in v4.8, therefore, add a local architectures
under 4.8 and remove `s390x` there
Signed-off-by: Yihong Wang <yh.wang@ibm.com>
=> Support s390x architecture

4.8/Dockerfile, 4.8/stretch/Dockerfile, 6.11/Dockerfile, 6.11/stretch/Dockerfile, 7.10/Dockerfile, 7.10/stretch/Dockerfile, 8.2/Dockerfile, 8.2/stretch/Dockerfile, Dockerfile-stretch.template, Dockerfile.template, architectures, functions.sh, update.sh
Support arm64 in all of the version and the following
variants: default, alpine, stretch, slim and onbuild
Generate proper architectures for the stackbrew
Update update.sh in order to be used on arm64
Signed-off-by: Zhao Longquan   zhaolongquan@huawei.com
=> Support arm64 architecture 

4.8/Dockerfile, 4.8/architectures, 4.8/slim/Dockerfile, 4.8/stretch/Dockerfile, 6.11/Dockerfile, 6.11/slim/Dockerfile, 6.11/stretch/Dockerfile, 7.10/Dockerfile, 7.10/slim/Dockerfile, 7.10/stretch/Dockerfile, 8.4/Dockerfile, 8.4/slim/Dockerfile, 8.4/stretch/Dockerfile, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile.template, architectures, functions.sh, update.sh
- Support arm32v7 in all versions and the following
variants: default, stretch, slim and onbuild
- Generate proper architectures for the stackbrew
- Update update.sh in order to be used on arm32v7
=> Support arm32v7 architecture

8.5/Dockerfile, 8.5/alpine/Dockerfile, 8.5/slim/Dockerfile, 8.5/stretch/Dockerfile, 8.5/wheezy/Dockerfile
This includes a particularly critical bug fix for private packages: https://github.com/yarnpkg/yarn/issues/4422
=> Update Yarn to 1.0.2 for Node 8.5

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/stretch/Dockerfile, 4.8/wheezy/Dockerfile, 6.11/Dockerfile, 6.11/alpine/Dockerfile, 6.11/slim/Dockerfile, 6.11/stretch/Dockerfile, 6.11/wheezy/Dockerfile, 8.7/Dockerfile, 8.7/alpine/Dockerfile, 8.7/slim/Dockerfile, 8.7/stretch/Dockerfile, 8.7/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile-wheezy.template, Dockerfile.template
=> Revert log level to npm's default level

docs/BestPractices.md
It took me a while to figure out why process handlers in my Node app were not received and following the best practices solved it for no apparent reason. More information in [this npm issue](https://github.com/npm/npm/issues/4603#issuecomment-170175517), TL;DR: npm does not pass on exit signals to its children.
Hopefully adding this information will save other people time debugging. :)
=> Add exit signal handling benefit to CMD section

README.md
=> Updated documentation for new log level

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/onbuild/Dockerfile, 4.8/slim/Dockerfile, 4.8/stretch/Dockerfile, 4.8/wheezy/Dockerfile, 6.11/Dockerfile, 6.11/alpine/Dockerfile, 6.11/onbuild/Dockerfile, 6.11/slim/Dockerfile, 6.11/stretch/Dockerfile, 6.11/wheezy/Dockerfile, 8.8/Dockerfile, 8.8/alpine/Dockerfile, 8.8/onbuild/Dockerfile, 8.8/slim/Dockerfile, 8.8/stretch/Dockerfile, 8.8/wheezy/Dockerfile, generate-stackbrew-library.sh
See https://nodejs.org/en/blog/vulnerability/oct-2017-dos/
=> Upgrade to node 4.8.5, 6.11.5, and 8.8.0 with yarn 1.2.1 to fix a DOS security vulnerability

4.8/Dockerfile, 4.8/alpine/Dockerfile, 4.8/slim/Dockerfile, 4.8/stretch/Dockerfile, 4.8/wheezy/Dockerfile, 6.11/Dockerfile, 6.11/alpine/Dockerfile, 6.11/slim/Dockerfile, 6.11/stretch/Dockerfile, 6.11/wheezy/Dockerfile, 8.8/Dockerfile, 8.8/alpine/Dockerfile, 8.8/slim/Dockerfile, 8.8/stretch/Dockerfile, 8.8/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile-wheezy.template, Dockerfile.template
Looks like we need to update the GPG key first to make the new release in #563 pass the test.
Ref: https://github.com/nodejs/node#release-team
=> Update GPG keys

4.8/architectures, 6.11/architectures, architectures
=> Add alpine to multi-arch support

4.8/Dockerfile, 4.8/architectures, 4.8/slim/Dockerfile, 4.8/stretch/Dockerfile, 6.11/Dockerfile, 6.11/architectures, 6.11/slim/Dockerfile, 6.11/stretch/Dockerfile, 8.9/Dockerfile, 8.9/slim/Dockerfile, 8.9/stretch/Dockerfile, 9.0/Dockerfile, 9.0/slim/Dockerfile, 9.0/stretch/Dockerfile, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile.template, architectures
Fixes #574. I'm _pretty_ sure this is correct, but not 100%. Wheezy not included because of #567.
Diff for stackbrew:
<details>
```diff
diff --git i/library/node w/library/node
index 1c45afc..68efc55 100644
--- i/library/node
+++ w/library/node
@@ -4,122 +4,122 @@ Maintainers: The Node.js Docker Team <https://github.com/nodejs/docker-node> (@n
GitRepo: https://github.com/nodejs/docker-node.git
Tags: 9.0.0, 9.0, 9, latest
-Architectures: amd64, ppc64le, s390x, arm64v8, arm32v7
-GitCommit: 092306f6d035d53d7f087a1a671915aabc946c6f
+Architectures: amd64, ppc64le, s390x, arm64v8, arm32v7, i386
+GitCommit: d3557702c9f55d3180ad50788a05f153dc99ac1a
Directory: 9.0
Tags: 9.0.0-alpine, 9.0-alpine, 9-alpine, alpine
-Architectures: amd64, ppc64le, s390x, arm64v8, arm32v6
+Architectures: amd64, …
```
=> Add i386 arch support

update.sh
This problem didn't appear everytime, I'm not sure what's the reason why yet, but when it appears, and when last number in the nodejs version = 0, the origin `update.sh` will cause `v6.12.0` become `v6.12.` and `v9.1.0` become `v9.1.` in the Dockerfiles, which is weird and not correct.
This patch will make the latest version (`$fullVersion` in the script) `0` when it's empty.
=> Fix update.sh for empty patch version issue

4/Dockerfile, 4/alpine/Dockerfile, 4/slim/Dockerfile, 4/stretch/Dockerfile, 4/wheezy/Dockerfile, 6/Dockerfile, 6/alpine/Dockerfile, 6/slim/Dockerfile, 6/stretch/Dockerfile, 6/wheezy/Dockerfile, 8/Dockerfile, 8/alpine/Dockerfile, 8/slim/Dockerfile, 8/stretch/Dockerfile, 8/wheezy/Dockerfile, 9/Dockerfile, 9/alpine/Dockerfile, 9/slim/Dockerfile, 9/stretch/Dockerfile, 9/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile-wheezy.template, Dockerfile.template
Building the base image from scratch starting from the source in a proxied environment, it can cause issues using gpg to import keys, this MR address the issue by changing the gpg host port to 80 and adding the protocol.
Refs: https://unix.stackexchange.com/questions/75892/keyserver-timed-out-when-trying-to-add-a-gpg-public-key
=> Better support of gpg keys installation behind a proxy

4/Dockerfile, 4/alpine/Dockerfile, 4/slim/Dockerfile, 4/stretch/Dockerfile, 4/wheezy/Dockerfile, 6/Dockerfile, 6/alpine/Dockerfile, 6/slim/Dockerfile, 6/stretch/Dockerfile, 6/wheezy/Dockerfile, 8/Dockerfile, 8/alpine/Dockerfile, 8/slim/Dockerfile, 8/stretch/Dockerfile, 8/wheezy/Dockerfile, 9/Dockerfile, 9/alpine/Dockerfile, 9/slim/Dockerfile, 9/stretch/Dockerfile, 9/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile-wheezy.template, Dockerfile.template
Related to https://github.com/nodejs/docker-node/pull/622
=> Use p80 and ipv4 pool.sks-keyservers.net  to avoid alpine gpg dns resolution

.travis.yml, 6/Dockerfile, 8/slim/Dockerfile, Dockerfile-stretch.template, chakracore/8/Dockerfile, chakracore/Dockerfile.template, chakracore/architectures, chakracore/config, config, functions.sh, generate-stackbrew-library.sh, test-build.sh, update.sh
This PR adds the Dockerfile for a single flavor (amd64/jessie) for node-chakracore.
I've run the `test-build.sh` script on Ubuntu 16.04 with success, but I don't think this file is currently compatible with the `update.sh` script.
/cc @aruneshchandra @digitalinfinity
=> Add Dockerfile for node-chakracore

update.sh
=> Use "exit" instead of "continue" to exit subshell in update.sh

4/Dockerfile, 4/alpine/Dockerfile, 4/slim/Dockerfile, 4/stretch/Dockerfile, 4/wheezy/Dockerfile, 6/Dockerfile, 6/alpine/Dockerfile, 6/slim/Dockerfile, 6/stretch/Dockerfile, 6/wheezy/Dockerfile, 8/Dockerfile, 8/alpine/Dockerfile, 8/slim/Dockerfile, 8/stretch/Dockerfile, 8/wheezy/Dockerfile, 9/Dockerfile, 9/alpine/Dockerfile, 9/slim/Dockerfile, 9/stretch/Dockerfile, 9/wheezy/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile-wheezy.template, Dockerfile.template, chakracore/8/Dockerfile, chakracore/Dockerfile.template
This drops the problematic `keyserver.pgp.com` gpg server (per https://github.com/docker-library/official-images/pull/4006#issuecomment-365420103) and reorders the server list to try the `*.pool.sks-keyservers.net` servers first, starting with `p80.pool.sks-keyservers.net:80`.
=> Drop keyserver.pgp.com and reorder pgp key servers

Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile-wheezy.template, Dockerfile.template, docs/BestPractices.md
this will allow for an easier upgrade of yarn, e.g:
```
FROM node:6-slim
ENV YARN_VERSION 1.5.1
RUN curl -fSLO --compressed
"https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz"
&&\
tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ &&\
ln -snf /opt/yarn-v$YARN_VERSION /opt/yarn &&\
rm yarn-v$YARN_VERSION.tar.gz
```
I will gladly apply this change across all Dockerfiles if this approach is approved.
=> Symlink yarn directory

chakracore/8/Dockerfile
- https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-v8.10.0
=> Update chakracore to v8.10.0 with yarn v1.5.1

.travis.yml, generate-stackbrew-pr.sh, travis.yml.template
=> Added a deploy stage to automate the deployment to the official images repo

.travis.yml
Travis CI started to provide ShellCheck directly for a while, we can save both time and resources to manually install it now!
=> Remove manual ShellCheck installation on Travis CI

generate-stackbrew-library.sh
Gives the following stackbrew diff:
```diff
@@ -1,34 +1,34 @@
-# this file is generated via https://github.com/nodejs/docker-node/blob/e839bbbb50d4969cfe68f95136354b0a6221ca7b/generate-stackbrew-library.sh
+# this file is generated via https://github.com/nodejs/docker-node/blob/a17e3f48d012804a98e961691d836bc721728e8e/generate-stackbrew-library.sh
Maintainers: The Node.js Docker Team <https://github.com/nodejs/docker-node> (@nodejs)
GitRepo: https://github.com/nodejs/docker-node.git
-Tags: 9.11.1, 9.11, 9, latest
+Tags: 9.11.1, 9.11, 9
Architectures: amd64, ppc64le, s390x, arm64v8, arm32v7, i386
GitCommit: 9023f588717d236a92d91a8483ff0582484c22d1
Directory: 9
-Tags: 9.11.1-alpine, 9.11-alpine, 9-alpine, alpine
+Tags: 9.11.1-alpine, 9.11-alpine, 9-alpine
Architectures: amd64, ppc64le, …
```
=> fix node 10 tags

generate-stackbrew-pr.sh
Clones the official-images repo in the parent repo instead of the current one to avoid the clone folder being picked up by the stackbrew-library script.
=> Fixed the stackbrew PR causing invalid stackbrew library entries

.travis.yml, travis.yml.template
=> Use LTS version of Node.js for doctoc

functions.sh, generate-stackbrew-library.sh, generate-stackbrew-pr.sh, test-build.sh, update.sh
Working on readability and maintainability.
=> Improve coding style of shell scripts

update.sh
=> Fix the update script for only a specific version

10/Dockerfile, 10/alpine/Dockerfile, 10/slim/Dockerfile, 10/stretch/Dockerfile, 6/Dockerfile, 6/alpine/Dockerfile, 6/slim/Dockerfile, 6/stretch/Dockerfile, 8/Dockerfile, 8/alpine/Dockerfile, 8/slim/Dockerfile, 8/stretch/Dockerfile, 9/Dockerfile, 9/alpine/Dockerfile, 9/slim/Dockerfile, 9/stretch/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile-stretch.template, Dockerfile.template, chakracore/10/Dockerfile, chakracore/8/Dockerfile, chakracore/Dockerfile.template
This makes curl less verbose by adding the `-s` flag (while still preserving errors). Previously curl would output the progress meter which wasn't really necessary. This PR also ensures we always use the `-f` and `--compressed` flags.
These changes might help a little bit with travis-ci build times and also adds some consistency to how we use curl.
=> Shush curl

Dockerfile-alpine.template, config, update.sh
=> Simplify the management of alpine version

10/Dockerfile, 10/alpine/Dockerfile, 10/slim/Dockerfile, 10/stretch/Dockerfile
Includes Yarn update for 1.7.0
=> Update for Node.js v10.2.0

chakracore/10/Dockerfile
- https://nodejs.org/download/chakracore-release/v10.1.0/
- https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-v10.1.0
=> Update chakracore to v10.1.0 with Yarn v1.7.0

.travis.yml, functions.sh, generate-stackbrew-pr.sh, travis.yml.template
=> Skip the images build when no images changed

10/alpine/Dockerfile, 10/jessie/Dockerfile, 10/slim/Dockerfile, 10/stretch/Dockerfile
- https://github.com/nodejs/node/releases/tag/v10.3.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.3.0
=> Update node.js v10.x to v10.3.0

.travis.yml
Git uses `..` but Travis CI uses `...`, cc #747
=> Adjust $TRAVIS_COMMIT_RANGE for git

test-build.sh, test-image.sh
This closes #768
I did some local testing by breaking one of the images (e.g., remove the yarn symlinks) and ran `test-build.sh` and it seems to work. I can do follow up commits that deliberately break the yarn, npm or node tests to verify that things work as expected in travis-ci. If all looks good I can rebase and drop those commits.
=> Fix image tests

.travis.yml, travis.yml.template
We don't need the latest Docker, instead, let's make the CI faster and less chance to fail.
=> Use default Docker version on Travis CI instead of manual install

update.sh
This adds a new `-s` option argument (and usage) to `update.sh` that allows you to skip updating the Yarn and Alpine versions when updating the images for a security release.
I also updated the shebang to match the other scripts and to ensure you get a newer (i.e. homebrew installed) version of bash when on a mac.
=> Add skip/security option to update.sh

config
Alpine Linux v3.8 Docker image released.
=> Bump Alpine base image version to v3.8

.travis.yml, travis.yml.template
Origin one is out of our control, and currently dated(v2.4.0).
After moved to v2.5.0, I'd like to enable `-sr` parameter to keep a space follow redirect operator.
=> Update shfmt Docker image on Travis CI

10/alpine/Dockerfile, 10/jessie/Dockerfile, 10/slim/Dockerfile, 10/stretch/Dockerfile
- Update node.js v10.x to v10.7.0
- For Alpine based image, update Alpine from v3.7 to v3.8
Ref:
- https://github.com/nodejs/node/releases/tag/v10.7.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.7.0
=> Update node.js v10 images

chakracore/10/Dockerfile
https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-v10.6.0
/cc @kfarnung
=> Update chakracore v10 to v10.6.0

.travis.yml, travis.yml.template
`find -exec` will not return the exit status of the callee program but `xargs` will, we need the second one to fail the CI when something going wrong.
=> Use `xargs` instead of `find -exec` for tests to return exit status

8/architectures
This copies the current `architectures` file into `8/` and then removes `i386` from all but Alpine (where it's built from source).
The justification here is that https://nodejs.org/dist/v10.6.0/node-v10.6.0-linux-x86.tar.xz is a 404 (appears 32bit builds are no longer generated).
=> Remove i386 support from binary-release-based 10 variants

6/architectures, 8/architectures, architectures
See https://wiki.debian.org/LTS for the list of supported "Debian Jessie" architectures (currently "i386, amd64, armel and armhf").
IMO, these `architectures` files appear to be very hard to keep current and accurate -- it took me some time to figure out whether this change was actually accurate given that these files are the _result_ of combining two bits of information.  On the one hand, you've got the list of architectures supported by Node.js (either in the binary releases in the case of Debian-based variants or for building from source in the case of Alpine-based variants) and on the other hand you've got the list of supported architectures for the base distribution each variant is building from.  Once you have those two bits of information, calculating the intersection of them is …
=> Remove "jessie" from unsupported architectures

10/alpine/Dockerfile, 10/jessie/Dockerfile, 10/slim/Dockerfile, 10/stretch/Dockerfile
https://github.com/nodejs/node/releases/tag/v10.13.0
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.13.0
=> Update node.js v10.x to v10.13.0

.travis.yml, travis.yml.template
Trusty is reaching EOL, Xenial environment is finally available, so let's move forward!
Ref: https://blog.travis-ci.com/2018-11-08-xenial-release
=> Update Travis CI environment to Ubuntu Xenial

8/alpine/Dockerfile, 8/architectures, 8/jessie/Dockerfile, 8/onbuild/Dockerfile, 8/slim/Dockerfile, 8/stretch/Dockerfile
- https://github.com/nodejs/node/releases/tag/v8.13.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.13.0
=> Update node@8.x to 8.13.0 w/ Yarn v1.12.3 and Stretch based images

10/alpine/Dockerfile, 11/alpine/Dockerfile, 6/alpine/Dockerfile, 8/alpine/Dockerfile, Dockerfile-alpine.template
This can prevent the build failed when there is no outside netcat
listening for cache transferring.
cc #918
=> Fix Alpine build w/ missing `|| true` when no netcat listening

docs/BestPractices.md
Continuing the conversation on:
https://github.com/nodejs/docker-node/issues/282
This PR adds code sample to the docs on how to use node-gyp dependencies on the alpine variant
=> Adds documentation for using node-gyp in alpine release

docs/BestPractices.md
I think the slash at the end of the line is typo which causes the second RUN to be on the same line as the previous RUN, which causes an error.
=> documentation: fix typo in recommended multistage Dockerfile

docs/BestPractices.md
realized there was another minor typo apline should be alpine
=> documentation: additional typo fix

10/alpine/Dockerfile, 10/jessie-slim/Dockerfile, 10/jessie/Dockerfile, 10/stretch-slim/Dockerfile, 10/stretch/Dockerfile, 11/alpine/Dockerfile, 11/stretch-slim/Dockerfile, 11/stretch/Dockerfile, 6/alpine/Dockerfile, 6/jessie-slim/Dockerfile, 6/jessie/Dockerfile, 6/onbuild/Dockerfile, 6/stretch-slim/Dockerfile, 6/stretch/Dockerfile, 8/alpine/Dockerfile, 8/jessie-slim/Dockerfile, 8/jessie/Dockerfile, 8/onbuild/Dockerfile, 8/stretch-slim/Dockerfile, 8/stretch/Dockerfile
https://github.com/nodejs/node/releases/tag/v11.10.1
https://github.com/nodejs/node/releases/tag/v10.15.2
https://github.com/nodejs/node/releases/tag/v8.15.1
https://github.com/nodejs/node/releases/tag/v6.17.0
Close #996
=> Update node.js v6, v8, v10 & v11 for security release

11/architectures, 6/architectures, 8/architectures, architectures
The contents of these files were generated by cross-referencing the available artifacts on https://nodejs.org/dist/ vs the supported architectures of the base image of each variant.
Closes #985
I would again echo my distaste for the overly-complex and confusing structure of these files that I articulated in https://github.com/nodejs/docker-node/pull/863.  IMO it would _much_ cleaner and simpler to maintain a list of mappings from "bashbrew architecture" string to "node architecture" string (which is a trivial list of 7 simple mappings) and generate the rest of the missing information based on detection (checking the release folder and then cross-referencing it with the supported architectures of the base image, which is exactly what my script did to generate these based on that list of 7 …
=> Update architectures files (generated)

Dockerfile-alpine.template
=> Disable `make` verbose mode in Alpine Dockerflie template

12/alpine/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile
- https://nodejs.org/en/blog/release/v12.3.0/
- https://github.com/nodejs/node/releases/tag/v12.3.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.3.0
=> Update node.js v12.2.0 to v12.3.0 with Yarn v1.16.0

.travis.yml, 10/architectures, 10/buster-slim/Dockerfile, 10/buster-slim/docker-entrypoint.sh, 10/buster/Dockerfile, 10/buster/docker-entrypoint.sh, 12/architectures, 12/buster-slim/Dockerfile, 12/buster-slim/docker-entrypoint.sh, 12/buster/Dockerfile, 12/buster/docker-entrypoint.sh, 8/architectures, 8/buster-slim/Dockerfile, 8/buster-slim/docker-entrypoint.sh, 8/buster/Dockerfile, 8/buster/docker-entrypoint.sh, architectures, config
New stable release Debian 10 "buster" was released 2019-07-06.  Add new "buster" and "buster-slim" image variants for all currently supported Node.js versions (v8, v10, v12).
This is basically #1055 redone without unrelated changes. The buster image variants use same Yarn as current stretch images are using.
This does not change the default variant. However I'd like to repeat part of what I commented in #1055.
Node.js v12.x LTS ends 2022-04-01, which is later than Debian 9 stretch ordinary security support (one year from the release of Debian 10 buster), but no later than Debian 9 stretch LTS support (June 2022).
However in my opinion preferred solution is to switch `node:12` and `node:12-slim` images to use Debian 10 buster before Node.js v12.x enters active LTS period on 2019-10-22.  In …
=> Add Debian 10 buster images

12/alpine/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile
- https://nodejs.org/en/blog/release/v12.7.0/
- https://github.com/nodejs/node/releases/tag/v12.7.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.7.0
=> Update node.js v12.6.0 to v12.7.0 with Yarn v1.17.3

10/alpine/Dockerfile, 10/buster-slim/Dockerfile, 10/buster/Dockerfile, 10/jessie-slim/Dockerfile, 10/jessie/Dockerfile, 10/stretch-slim/Dockerfile, 10/stretch/Dockerfile, 12/alpine/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile
Update node.js v10 from v10.16.1 to v10.16.2
- https://nodejs.org/en/blog/release/v10.16.2/
- https://github.com/nodejs/node/releases/tag/v10.16.2
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.16.2
Update node.js v12 from v12.6.0 to v12.7.0
- https://nodejs.org/en/blog/release/v12.7.0/
- https://github.com/nodejs/node/releases/tag/v12.7.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.7.0
=> Update node.js v10 & v12

ACTIVE_MAINTAINERS, README.md
Hi!
I don't exactly know what the process for this is, but I will no longer be able to be an active member of the Docker Working Group. I'm updating the README.md to reflect my current status.
=> meta: move chorrell to Docker Working Group Emeriti list

README.md
The current recommend node version is 10.
Source: https://nodejs.org/en/
So don't have a competing recommendation in this file.
=> Switch to recommend node version

docs/BestPractices.md
`CTRL-C` sends `SIGINT` signal, not `SIGTERM`.
=> docs(BestPractices.md/Handling Kernel Signals): fix

12/alpine/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile
- https://nodejs.org/en/blog/release/v12.11.0/
- https://github.com/nodejs/node/releases/tag/v12.11.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.11.0
=> Update node.js v12 from v12.10.0 to v12.11.0

.travis.yml, travis.yml.template
Originally it supports only Dockerfile changes, with this adjustment,
it'll now send pull request to the downstream for the version and tag
array in generate-stackbrew-library.sh file.
cc #1134
=> Improve Travis CI deploy/send PR condition

Dockerfile-alpine.template
As suggested by @tianon in docker-library/official-images#6871
=> Replace`arch` with `apk --print-arch` in Dockerfile-alpine.template

config
Ref:
- https://alpinelinux.org/posts/Alpine-3.10.0-released.html
- https://alpinelinux.org/posts/Alpine-3.10.1-released.html
cc #1061 #1075
=> Update Alpine Linux version to v3.10 in config

generate-stackbrew-pr.sh
From @tianon comment on https://github.com/nodejs/docker-node/pull/1148#issuecomment-553742296 since this gets asked by people when they see the merged PR in this repo
=> chore: pointer to official images process docs

.travis.yml, 13/architectures, 8/architectures, architectures
This addresses the failure from https://github.com/docker-library/official-images/pull/6972#discussion_r346550004.
<details>
<summary>Diff:</summary>
```diff
$ diff -u <(bashbrew cat node) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2019-11-14 13:22:15.381053187 -0800
+++ /dev/fd/62	2019-11-14 13:22:15.381053187 -0800
@@ -11,16 +11,6 @@
GitCommit: fa27514a3fd775e1cb6bddac326f6f97dad05fb2
Directory: 8/jessie-slim
-Tags: 8.16.2-alpine, 8.16-alpine, 8-alpine, carbon-alpine
-Architectures: amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x
-GitCommit: 93c5e098567620200e5a374622a86b4aff153506
-Directory: 8/alpine
-
-Tags: 8.16.2-onbuild, 8.16-onbuild, 8-onbuild, carbon-onbuild
-Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
-GitCommit: …
```
=> Fix architectures lists for consistency and correctness

SECURITY.md
Just an initial pass to get something up
=> chore: Add initial SECURITY.md

update.sh
Invoking update.sh with `slim` variant did not work, because slim
variants are always tied to Debian version (e.g. stretch, buster).
=> Fix update.sh example with slim

13/alpine3.10/Dockerfile, 13/buster-slim/Dockerfile, 13/buster/Dockerfile, 13/stretch-slim/Dockerfile, 13/stretch/Dockerfile
- https://nodejs.org/en/blog/release/v13.3.0/
- https://github.com/nodejs/node/releases/tag/v13.3.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.3.0
cc #1163
=> Update node.js v13 to v13.3.0 with Yarn v1.19.2

10/alpine3.10/Dockerfile, 10/alpine3.9/Dockerfile, 10/buster-slim/Dockerfile, 10/buster/Dockerfile, 10/jessie-slim/Dockerfile, 10/jessie/Dockerfile, 10/stretch-slim/Dockerfile, 10/stretch/Dockerfile, 12/alpine3.10/Dockerfile, 12/alpine3.9/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile, 13/alpine3.10/Dockerfile, 13/buster-slim/Dockerfile, 13/buster/Dockerfile, 13/stretch-slim/Dockerfile, 13/stretch/Dockerfile, 8/alpine3.10/Dockerfile, 8/alpine3.9/Dockerfile, 8/buster-slim/Dockerfile, 8/buster/Dockerfile, 8/jessie-slim/Dockerfile, 8/jessie/Dockerfile, 8/onbuild/Dockerfile, 8/stretch-slim/Dockerfile, 8/stretch/Dockerfile, chakracore/10/Dockerfile, chakracore/8/Dockerfile
For < 13, npm is being updated to address vulnerabilities.
For 13, its the normal release contents, including the npm update.
I created this PR by following the directions in https://github.com/nodejs/node/blob/master/doc/guides/security_release_process.md#release-day
> Create a PR to update the Node.js version in the official docker images.
> ....
> Run the update.sh using the -s option so that ONLY the Node.js versions are updated. At the request from docker (and because it is good practice) we limit the changes to those necessary in security updates.
Please review it carefully. I'm not entirely sure how to interpret the directions. Should I be editing the result of the `update.sh -s`?
For example,
- I notice some CHECKSUM strings are now empty, is this functioning correctly?
- I notice …
=> Update Node.js 8, 10, 12, 13 for 2019-12 security

CONTRIBUTING.md
@PeterDaveHello brought up a great point in https://github.com/nodejs/docker-node/pull/1170#discussion_r359206734 - our current policy states that we only update yarn when there's new releases of node. I somewhat regret just moving on instead of backing out those changes and discussing. However, I think we _should_ update it on security updates, so here's a PR with a policy update
=> docs: update contributing to mentions security yarn releases

10/buster-slim/Dockerfile, 10/jessie-slim/Dockerfile, 10/stretch-slim/Dockerfile, 12/buster-slim/Dockerfile, 12/stretch-slim/Dockerfile, 13/buster-slim/Dockerfile, 13/stretch-slim/Dockerfile, Dockerfile-slim.template
Should fix #1181.
/cc @tianon does this make sense?
=> fix: uninstall download helpers from slim image

12/alpine3.10/Dockerfile, 12/alpine3.11/Dockerfile, 12/alpine3.9/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile, 13/alpine3.10/Dockerfile, 13/alpine3.11/Dockerfile, 13/buster-slim/Dockerfile, 13/buster/Dockerfile, 13/stretch-slim/Dockerfile, 13/stretch/Dockerfile
https://nodejs.org/en/blog/release/v12.14.1/
---
13.6.0 is also out, but the alpine image isn't ready yet. @nodejs/docker feel free to push that if it's released before this is merged
=> Update node.js v12 to v12.14.1 and v13 to 13.6.0

update.sh
If update.sh was invoked with non-existing variant, it updated all
variants.  Change in_variants_to_update to return true always if
second variant argument was not given, but not when given variant
argument does not match to available variants.
=> Fix update.sh invocation with unknown variant

.github/workflows/doctoc.yml, .github/workflows/eclint.yml, .github/workflows/markdown-link-check.yml, .github/workflows/shfmt.yml, .travis.yml, travis.yml.template
Pulls a few of the minor ones over to GitHub actions to reduce the Travis load. This also has a little better built in job filtering, so if affected files in the "path" values doesn't match, it doesn't even launch a job.
I did some testing on the path executions on my fork, but I can add some dummy commits to show it if you want.
=> GitHub actions

13/alpine3.10/Dockerfile, 13/alpine3.11/Dockerfile
v13 update for Alpine Linux was missing due to the delay of unofficial
build for Alpine.
, cc #1209
=> Update Node.js v13 for Alpine to v13.8.0

10/alpine3.10/Dockerfile, 10/alpine3.11/Dockerfile, 10/alpine3.9/Dockerfile, 10/buster-slim/Dockerfile, 10/buster/Dockerfile, 10/jessie-slim/Dockerfile, 10/jessie/Dockerfile, 10/stretch-slim/Dockerfile, 10/stretch/Dockerfile, 12/alpine3.10/Dockerfile, 12/alpine3.11/Dockerfile, 12/alpine3.9/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile, 13/alpine3.10/Dockerfile, 13/alpine3.11/Dockerfile, 13/buster-slim/Dockerfile, 13/buster/Dockerfile, 13/stretch-slim/Dockerfile, 13/stretch/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template, chakracore/10/Dockerfile, chakracore/Dockerfile.template
Second part of https://github.com/nodejs/docker-node/issues/1195#issuecomment-573866812
=> chore: add smoke tests to the images

12/alpine3.10/Dockerfile, 12/alpine3.11/Dockerfile, 12/alpine3.9/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile
https://nodejs.org/en/blog/release/v12.16.1/
13.9 has been released as well (https://github.com/nodejs/node/releases/tag/v13.9.0) but no blog post or Alpine release yet
=> chore: upgrade to node 12.16.1

10/buster-slim/Dockerfile, 10/jessie-slim/Dockerfile, 10/stretch-slim/Dockerfile, 12/buster-slim/Dockerfile, 12/stretch-slim/Dockerfile, 13/buster-slim/Dockerfile, 13/stretch-slim/Dockerfile, Dockerfile-slim.template
Should be merged after #1197. I kept them separate as I don't know how to test that this works for arm.
Fixes #1195
=> fix: keep dynamically linked files in slim images

13/alpine3.10/Dockerfile, 13/alpine3.11/Dockerfile, 13/buster-slim/Dockerfile, 13/buster/Dockerfile, 13/stretch-slim/Dockerfile, 13/stretch/Dockerfile
- https://nodejs.org/en/blog/release/v13.10.1/
- https://github.com/nodejs/node/releases/tag/v13.10.1
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.10.1
=> Update node.js v13.x to v13.10.1 with Yarn v1.22.1

.travis.yml, 14/alpine3.10/Dockerfile, 14/alpine3.10/docker-entrypoint.sh, 14/alpine3.11/Dockerfile, 14/alpine3.11/docker-entrypoint.sh, 14/architectures, 14/buster-slim/Dockerfile, 14/buster-slim/docker-entrypoint.sh, 14/buster/Dockerfile, 14/buster/docker-entrypoint.sh, 14/stretch-slim/Dockerfile, 14/stretch-slim/docker-entrypoint.sh, 14/stretch/Dockerfile, 14/stretch/docker-entrypoint.sh, generate-stackbrew-library.sh
https://medium.com/@nodejs/node-js-version-14-available-now-8170d384567e
`git mv 13 14`, update in `generate-stackbrew-library` and run `./update.sh`. Not sure there's anything else? Should we remove stretch and/or alpine 3.10?
=> feat: add node 14

generate-stackbrew-library.sh
why is 12 `current`? do we mean it's `current lts`? `current` in node terms is equivalent to `latest` in docker terms.
=> chore: tag node v14 as current

update-keys.sh
=> Add update-keys.sh for nodejs release keys update

functions.sh
Config handling script had some unnecessary complicated logic as leftover from removed chakracode configs where subdir (chakracore specific variants) had versions, which is removed here
=> Remove chakracore config leftovers

14/alpine3.10/Dockerfile, 14/alpine3.11/Dockerfile, 14/alpine3.12/Dockerfile, 14/buster-slim/Dockerfile, 14/buster/Dockerfile, 14/stretch-slim/Dockerfile, 14/stretch/Dockerfile
- https://nodejs.org/en/blog/release/v14.9.0/
- https://github.com/nodejs/node/releases/tag/v14.9.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.9.0
=> Update node.js v14 from 14.8.0 to 14.9.0

10/alpine3.10/Dockerfile, 10/alpine3.11/Dockerfile, 10/alpine3.9/Dockerfile, 12/alpine3.10/Dockerfile, 12/alpine3.11/Dockerfile, 12/alpine3.12/Dockerfile, 12/alpine3.9/Dockerfile, 14/alpine3.10/Dockerfile, 14/alpine3.11/Dockerfile, 14/alpine3.12/Dockerfile, Dockerfile-alpine.template, update.sh
In alpine3.12, they removed the python package in favor of either python2 or python3.
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.12.0#python2_no_longer_provides_python_and_python-devel
Refs #1330
=> fix: use python3 or python2 for alpine

12/architectures, 14/architectures
Official support stopped in v8 and is currnetly all failing in the
official-images CI.
Can be re-enabled if support is fixed
=> fix: Remove 386 architecture for v12 and v14

15/alpine3.10/Dockerfile, 15/alpine3.10/docker-entrypoint.sh, 15/alpine3.11/Dockerfile, 15/alpine3.11/docker-entrypoint.sh, 15/alpine3.12/Dockerfile, 15/alpine3.12/docker-entrypoint.sh, 15/architectures, 15/buster-slim/Dockerfile, 15/buster-slim/docker-entrypoint.sh, 15/buster/Dockerfile, 15/buster/docker-entrypoint.sh, 15/stretch-slim/Dockerfile, 15/stretch-slim/docker-entrypoint.sh, 15/stretch/Dockerfile, 15/stretch/docker-entrypoint.sh, config, generate-stackbrew-library.sh
https://nodejs.org/en/blog/release/v15.0.0/
We need to wait for the unofficial build: https://unofficial-builds.nodejs.org/download/release/v15.0.0/
I went with just buster and alpine 3.12 instead of keeping the others around. Happy to re-add if people think that's a good idea
=> feat: add node v15.0.0

config
This changed the defaults for all previous versions. This is a temporary workaround so we can get out the 15 release and look at the overall config management afterwards
=> fix: Revert default variant changes

architectures
- Remove slim architectures no longer supported
- Sort architecture names to match children
=> chore: Sort and sync default architecture file

10/alpine3.10/Dockerfile, 10/alpine3.11/Dockerfile, 10/alpine3.9/Dockerfile, 10/buster-slim/Dockerfile, 10/buster/Dockerfile, 10/stretch-slim/Dockerfile, 10/stretch/Dockerfile, 14/alpine3.10/Dockerfile, 14/alpine3.11/Dockerfile, 14/alpine3.12/Dockerfile, 14/buster-slim/Dockerfile, 14/buster/Dockerfile, 14/stretch-slim/Dockerfile, 14/stretch/Dockerfile, generate-stackbrew-library.sh
https://nodejs.org/en/blog/release/v10.23.0/
https://nodejs.org/en/blog/release/v14.15.0/
v14 is now LTS. Alpine build is not ready yet.
https://unofficial-builds.nodejs.org/download/release/v14.15.0/
https://unofficial-builds.nodejs.org/download/release/v10.23.0/ ~does not exist ATM for some reason~
=> chore: update to v10.23.0 & v14.15.0

.github/workflows/official-pr.yml
I'd expect landing this will still show the message because of the `pull_request_target`
=> chore: Don't comment on PR for no-op

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/2-feature-request.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Added `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` in `.github`.
Closes #1214.
Closes #1346.
=> Added Issue and PR Templates

12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile, 14/buster-slim/Dockerfile, 14/buster/Dockerfile, 14/stretch-slim/Dockerfile, 14/stretch/Dockerfile, 15/buster-slim/Dockerfile, 15/buster/Dockerfile, 15/stretch-slim/Dockerfile, 15/stretch/Dockerfile
Not sure when the unofficial Node.js binary tarball for Alpine Linux will be ready, let's not delay the update for Debian based images.
References:
- https://nodejs.org/en/blog/release/v12.19.1
- https://nodejs.org/en/blog/release/v14.15.1
- https://nodejs.org/en/blog/release/v15.2.1
- https://nodejs.org/en/blog/vulnerability/november-2020-security-releases/
=> November 2020 Security Releases for Debian base images

12/alpine3.10/Dockerfile, 12/alpine3.11/Dockerfile, 12/alpine3.12/Dockerfile, 12/alpine3.9/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile, 15/alpine3.10/Dockerfile, 15/alpine3.11/Dockerfile, 15/alpine3.12/Dockerfile, 15/buster-slim/Dockerfile, 15/buster/Dockerfile, 15/stretch-slim/Dockerfile, 15/stretch/Dockerfile
Reference:
- https://nodejs.org/en/blog/release/v12.20.0/
- https://github.com/nodejs/node/releases/tag/v12.20.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.20.0
- https://nodejs.org/en/blog/release/v15.3.0/
- https://github.com/nodejs/node/releases/tag/v15.3.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#15.3.0
=> Update node.js v12 to v12.20.0 and v15 to v15.3.0

.github/workflows/official-pr.yml
Transfer happened in https://github.com/nodejs/admin/issues/562
I've already trimmed out the 90+ old `travis-*` branches. 
This should probably land before the security update PR, but that PR will need to be rebased I think before landing in order for the `pull_request_target` to work right (I think)
=> chore: Update official image fork to nodejs

16/alpine3.11/Dockerfile, 16/alpine3.11/docker-entrypoint.sh, 16/alpine3.12/Dockerfile, 16/alpine3.12/docker-entrypoint.sh, 16/alpine3.13/Dockerfile, 16/alpine3.13/docker-entrypoint.sh, 16/architectures, 16/buster-slim/Dockerfile, 16/buster-slim/docker-entrypoint.sh, 16/buster/Dockerfile, 16/buster/docker-entrypoint.sh, 16/stretch-slim/Dockerfile, 16/stretch-slim/docker-entrypoint.sh, 16/stretch/Dockerfile, 16/stretch/docker-entrypoint.sh
- removed **alpine v3.10** as it is **EOL** very soon: [2021-05-01](https://alpinelinux.org/releases/)
=> feat: node.js v16.0.0

architectures
Clean up Alpine 3.10 in architectures file, cc #1490
Those configs seem to be missed in the Alpine v3.10 drop in #1490
=> Clean up Alpine 3.10 in architectures file, cc #1490

12/alpine3.11/Dockerfile, 12/alpine3.12/Dockerfile, 12/buster-slim/Dockerfile, 12/buster/Dockerfile, 12/stretch-slim/Dockerfile, 12/stretch/Dockerfile, 14/alpine3.11/Dockerfile, 14/alpine3.12/Dockerfile, 14/alpine3.13/Dockerfile, 14/buster-slim/Dockerfile, 14/buster/Dockerfile, 14/stretch-slim/Dockerfile, 14/stretch/Dockerfile, 16/alpine3.11/Dockerfile, 16/alpine3.12/Dockerfile, 16/alpine3.13/Dockerfile, 16/buster-slim/Dockerfile, 16/buster/Dockerfile, 16/stretch-slim/Dockerfile, 16/stretch/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template, update-keys.sh
SKS servers are no longer working, so switches to alternates
=> chore: Use openpgp and Ubuntu keyservers

12/alpine3.13/Dockerfile, 12/alpine3.13/docker-entrypoint.sh, 12/alpine3.14/Dockerfile, 12/alpine3.14/docker-entrypoint.sh, versions.json
This PR add support for Node v12 on Alpine 3.13
Node v12 is still in LTS support and Alpine 3.13 has numerous security improvements, including accessing packages with `apk` via HTTPS instead of HTTP
I have been running v12 on this docker image for two production containers for the last 2 weeks
* Alpine 3.13 + Alpline 3.14 for Node 12
* Bumped NodeJS version to 12.22.1
=> Add node.js v12 on Alpine v3.13/v3.14

.gitattributes
Already set through EditorConfig, but the key replacement gets messed up on Windows with the initial CRLF checkout of files
=> chore: Add gitattributes for Git Bash LF checkout

stackbrew.js
Current script just takes the commit hash for the Dockerfile, so when the commit bit was fixed, it isn't getting picked up for the upstream PR. Now it will use the whole variant folder when looking for the latest commithash
=> fix: Use folder commmit for Stackbrew

update.sh
Clean up temporarily generated Dockerfiles in the update.sh before fatal exit
Currently, the fatal exit will leave the temporarily generated Dockerfiles, should be removed:
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
14/alpine3.14/Dockerfile-tmp
14/alpine3.15/Dockerfile-tmp
```
Run `./update.sh` with fatal error situation, and make sure the patched version left no additional temp files.
=> Clean up temp Dockerfile in update.sh before fatal exit

update.sh
Fix `update.sh` does not pick up new node release #1636 issue
We should use `sort -V` instead of `sort -n` here. The order is a little bit different:
| Result from `sort -V` | Result from `sort -n` |
| ---- | ---- |
| 0.0 | 0.0 |
| 1.0 | 1.0 |
| 2.0 | 2.0 |
| 3.0 | 3.0 |
| 3.1 | 3.1 |
| 4.0 | 4.0 |
| 5.0 | 5.0 |
| 6.0 | 6.0 |
| 7.0 | 7.0 |
| 8.0 | 8.0 |
| 8.1 | 8.1 |
| 9.0 | 9.0 |
| 9.1 | 9.1 |
| 10.0 | 10.0 |
| 11.0 | 11.0 |
| 11.1 | 11.1 |
| 12.0 | 12.0 |
| 13.0 | 13.0 |
| 13.1 | 13.1 |
| 14.0 | 14.0 |
| 14.1 | 14.1 |
| 15.0 | 15.0 |
| 16.0 | 16.0 |
| 16.1 | 16.1 |
| 16.2 | 16.2 |
| 16.3 | 16.3 |
| 17.0 | 17.0 |
| 18.0 | 18.0 |
| 18.1 | 18.1 |
| 18.2 | 18.2 |
| 18.3 | 18.3 |
| 18.4 | 18.4 |
| 19.0 | 19.0 |
| 19.1 | 19.1 |
| 20.0 | 20.0 |
| 20.1 | 20.1 |
| 20.2 | 20.2 |
| 21.0 | 21.0 |
| …
=> Use `-V` instead of `-n` to sort in update.sh, fix #1636

.github/workflows/doctoc.yml, .github/workflows/eclint.yml, .github/workflows/markdown-link-check.yml
12 is soon EOL, and just targeting `lts` means one less thing to keep up to date 🙂
=> chore: run all GH actions using Node LTS, not v12

update-keys.sh
Add awk escape sequences to opengpg key server url to update-keys.sh
The awk command in update-keys.sh was failing with the unescaped URL. 
Ran `./update-keys.sh` to confirm output to `keys/node.keys`
=> chore: add awk escapes for openpgp keyserver

.github/workflows/automatic-updates.yml, build-automation.mjs
See #1688 which is missing the versions. I think by returning JSON we need to parse it in the later step. Since we only use the string, returning that directly seems easier.
https://github.com/actions/github-script/blob/9bd6ae64c1b3b9677eba79c33befd8c1c45088c0/src/main.ts#L54
=> fix: get correct commit message and PR title for auto PRs

stackbrew.js
This will lose `current-stretch` and `current-stretch-slim` tags, since the "current" no longer has a stretch version. I think previously sometimes there would be a leftover of the overlapping `current`s
=> fix: use most Current/LTS with overlapping dates

.github/workflows/doctoc.yml, .github/workflows/eclint.yml, .github/workflows/markdown-link-check.yml, .github/workflows/missing-checksum.yml, .github/workflows/shfmt.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

config
I'm unsure if this is is correct, but without it, this fails to list v18 (meaning the update script doesn't work for the new 18.1.0)(which atm doesn't matter since musl build isn't done, but still))
```sh-session
$ source functions.js
$ get_versions
14 16 17
```
https://github.com/nodejs/docker-node/blob/494c3c3775b4385099a75abfe339b9efcbb1a970/functions.sh#L139-L156
(we really should rewrite these to JS 😅)
=> fix: set correct default distro

.github/workflows/markdown-link-check.yml, markdown_link_check_config.json
The workaround for the markdown-link-check lint
According to https://github.com/tcort/markdown-link-check/issues/201, GitHub now requires the behavior to accept compressed content, otherwise will return http 403 error, which caused markdown-link-check failed
=> Add markdown-link-check GitHub Docs workaround, cc #1739

versions.json
Buster is now LTS, so the supported architectures has been reduced by the official images
=> fix: remove ppc64le and s390x for buster

16/alpine3.16/Dockerfile, 16/alpine3.17/Dockerfile, 18/alpine3.16/Dockerfile, 18/alpine3.17/Dockerfile
This change fixes the SHA256 checksums for Node.js 16.19.1 and 18.14.1 based on Alpine 3.16 and 3.17.
Fixes https://github.com/nodejs/docker-node/issues/1853
=> fix checksums for Node.js 16.19.1 and 18.14.1 on Alpine 3.16 and 3.17

16/bookworm-slim/Dockerfile, 16/bookworm-slim/docker-entrypoint.sh, 16/bookworm/Dockerfile, 16/bookworm/docker-entrypoint.sh, 18/bookworm-slim/Dockerfile, 18/bookworm-slim/docker-entrypoint.sh, 18/bookworm/Dockerfile, 18/bookworm/docker-entrypoint.sh, 20/bookworm-slim/Dockerfile, 20/bookworm-slim/docker-entrypoint.sh, 20/bookworm/Dockerfile, 20/bookworm/docker-entrypoint.sh, README.md, SECURITY.md, architectures, config, update.sh, versions.json
Bookworm should be released soon, add it to debian variants.
=> Add images for debian bookworm

16/bookworm-slim/Dockerfile, 16/bullseye-slim/Dockerfile, 16/buster-slim/Dockerfile, 18/bookworm-slim/Dockerfile, 18/bullseye-slim/Dockerfile, 18/buster-slim/Dockerfile, 20/bookworm-slim/Dockerfile, 20/bullseye-slim/Dockerfile, 20/buster-slim/Dockerfile, Dockerfile-slim.template
Bookworm moved to [UsrMerge](https://wiki.debian.org/UsrMerge) by default. This means `/lib` is a symlink to `/usr/lib`, so some `ldd` returned paths need to be adjusted so that Debian can figure out which package it belongs to (since the package will report `/usr/lib...` now). The fix is backward compatible with Buster and Bullseye based images.
The same change was done for other Docker Official Images: https://github.com/docker-library/php/pull/1416, https://github.com/docker-library/wordpress/pull/834, https://github.com/docker-library/python/pull/822.
Without this, the `node:*-bookworm-slim` images fail to build on `arm32v7` (https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/node/):
```console
$ docker build --platform linux/arm/v7 20/bookworm-slim/
...
dpkg-query: no path …
```
=> Update `ldd|awk` to account for Bookworm's merged `/usr`

18/bookworm-slim/Dockerfile, 18/bookworm/Dockerfile, 18/bullseye-slim/Dockerfile, 18/bullseye/Dockerfile, 18/buster-slim/Dockerfile, 18/buster/Dockerfile, 20/bookworm-slim/Dockerfile, 20/bookworm/Dockerfile, 20/bullseye-slim/Dockerfile, 20/bullseye/Dockerfile, 20/buster-slim/Dockerfile, 20/buster/Dockerfile, Dockerfile-debian.template, Dockerfile-slim.template
As a follow-up to https://github.com/nodejs/docker-node/pull/1895#issuecomment-1550389150, this PR alters the debian-based images to use a temporary `GNUPGHOME` directory to be more consistent with other official image and possibly prevent future issues with new GPG versions.
Discussion on https://github.com/nodejs/docker-node/pull/1895.
=> Use temporary `GNUPGHOME` directory when using gpg in image builds

stackbrew.js
There's a few days between the start of the maintenance window if a previous LTS and the start date of a new LTS
Example:
Node 18 went on maintenance on October 18th but Node 20 doesn't become LTS until October 24th.
This lets a version in maintenance mode fill in the gap until the new LTS is active.
=> Fix the gap between the start of a maintenance period for an LTS and the new LTS start

18/bookworm-slim/Dockerfile, 18/bullseye-slim/Dockerfile, 18/buster-slim/Dockerfile, 20/bookworm-slim/Dockerfile, 20/bullseye-slim/Dockerfile, 20/buster-slim/Dockerfile, Dockerfile-slim.template
Remove unused OpenSSL headers for architectures other than current one
Remove unused OpenSSL headers for platforms other than current one (linux + machine_arch).
This is a mitigation for [this open NodeJS issue](https://github.com/nodejs/node/issues/46451).
To save a few 10s of MB in all slim images:
I tested the following command ran successfully:
```bash
docker run node:18-buster-slim-in-this-branch node -e "console.log(require('crypto').createHash('sha256').update('bla').digest('hex'))"
```
=> Remove unused openssl headers

README.md
Update Docker Compose example with ports usage, because might be useful.
Update Docker Compose example in readme.md with ports usage.
Ports might be useful to expose container to the host machine. This information is very important.
It's only readme.md update.
=> docs(README): Add ports mapping to Docker Compose example

build-automation.mjs
Avoid the extra network call per version as we have all the info needed from the `index.json` file.
See #2031
```js
// tested in repl which has TLA
const { Octokit } = require('@octokit/rest');
const github = new Octokit();
const { data: unofficialBuildsIndexText } = await github.request('https://unofficial-builds.nodejs.org/download/release/index.json');
const buildVersion = unofficialBuildsIndexText.find(indexVersion => indexVersion.version === 'v20.0.0');
console.log(buildVersion?.files.includes('linux-x64-musl'));
console.log(buildVersion?.security);
```
=> chore: avoid extra request when checking for MUSL builds

README.md, docs/BestPractices.md
Added punctuation for readability.
=> docs: added punctuation

.github/workflows/markdown-link-check.yml
Pin markdown-link-check to v3.11.0 in the GitHub Actions workflow to avoid incorrect 404 errors on existing section links.
Starting from markdown-link-check v3.12.1, there is a bug where it incorrectly reports 404 errors for valid existing section links in Markdown files, while v3.11.2 and older do not have this issue, as seen in the CI log:
https://github.com/nodejs/docker-node/actions/runs/8650084895/job/23717794438?pr=2066
To ensure our CI continues to function correctly without these false positive 404 errors, this PR pins the markdown-link-check version to v3.11.0 in the GitHub Actions workflow file.
The changes in this PR were tested by running the updated GitHub Actions workflow on a test branch. The previously occurring false positive 404 errors no longer appear after pinning …
=> Pin markdown-link-check to v3.11.0 on GitHub Actions

README.md
Starting from Alpine 3.19, the `gcompat` package should be used instead of `libc6-compat` to include missing shared libraries required for `process.dlopen`.
This change is based on the latest Alpine Linux 3.19.0 release notes: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.19.0
The `libc6-compat` package was removed in Alpine Linux 3.19 in favor of `gcompat` from Adélie Linux to provide GNU C library compatibility layer. This change is necessary to keep the documentation up-to-date and provide accurate information for users who need to add missing shared libraries for `process.dlopen` on Alpine 3.19 and later.
This change does not require additional testing as it only involves updating the documentation. The updated instructions have been verified by referring to the …
=> docs: update shared libs section for Alpine 3.19+

18/alpine3.18/Dockerfile, 18/alpine3.19/Dockerfile, 18/bookworm-slim/Dockerfile, 18/bookworm/Dockerfile, 18/bullseye-slim/Dockerfile, 18/bullseye/Dockerfile, 18/buster-slim/Dockerfile, 18/buster/Dockerfile, 20/alpine3.18/Dockerfile, 20/alpine3.19/Dockerfile, 20/bookworm-slim/Dockerfile, 20/bookworm/Dockerfile, 20/bullseye-slim/Dockerfile, 20/bullseye/Dockerfile, 20/buster-slim/Dockerfile, 20/buster/Dockerfile, 21/alpine3.18/Dockerfile, 21/alpine3.19/Dockerfile, 21/bookworm-slim/Dockerfile, 21/bookworm/Dockerfile, 21/bullseye-slim/Dockerfile, 21/bullseye/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
The /tmp folder contains a folder `v8-compile-cache-0` 2.2Mo
optimise the docker image version
tested locally to confirm the image size
=> Clean up /tmp folder to save about 2.2MB of space

versions.json
Need to confirm that this is required in #1885 so opening as draft for now
=> feat: drop arm32v7 buster for Node 20

22/alpine3.18/Dockerfile, 22/alpine3.18/docker-entrypoint.sh, 22/alpine3.19/Dockerfile, 22/alpine3.19/docker-entrypoint.sh, 22/bookworm-slim/Dockerfile, 22/bookworm-slim/docker-entrypoint.sh, 22/bookworm/Dockerfile, 22/bookworm/docker-entrypoint.sh, 22/bullseye-slim/Dockerfile, 22/bullseye-slim/docker-entrypoint.sh, 22/bullseye/Dockerfile, 22/bullseye/docker-entrypoint.sh, versions.json
Release for Node.js 22.0.0: https://nodejs.org/en/blog/release/v22.0.0
Based on https://github.com/nodejs/docker-node/pull/1882 and https://github.com/nodejs/docker-node/pull/1980
=> feat: Node.js 22.0.0

.gitattributes
Reverts nodejs/docker-node#2062
This means we need to click the "load diff" everywhere in the UI including the Commit view to see the actual changes. These files may be auto-generated in some cases, but we we need to verify the changes visually to ensure there are no intentional or unintentional malicious changes.
=> Revert "Hide auto-generated files in code reviews and format Dockerfile templates"

functions.sh, update.sh
Fixes #1848, but I'm not sure if it's the _correct_ fix.
If I set `arch` as `arm64`, I get this diff:
```diff
diff --git i/18/alpine3.18/Dockerfile w/18/alpine3.18/Dockerfile
index fb8836d..065cb4a 100644
--- i/18/alpine3.18/Dockerfile
+++ w/18/alpine3.18/Dockerfile
@@ -1,4 +1,4 @@
-FROM alpine:3.18
+FROM arm64/alpine:3.18
ENV NODE_VERSION 18.20.2
diff --git i/18/alpine3.19/Dockerfile w/18/alpine3.19/Dockerfile
index 22a2c85..4652a8f 100644
--- i/18/alpine3.19/Dockerfile
+++ w/18/alpine3.19/Dockerfile
@@ -1,4 +1,4 @@
-FROM alpine:3.19
+FROM arm64/alpine:3.19
ENV NODE_VERSION 18.20.2
diff --git i/18/bookworm-slim/Dockerfile w/18/bookworm-slim/Dockerfile
index 83f954b..be12682 100644
--- i/18/bookworm-slim/Dockerfile
+++ w/18/bookworm-slim/Dockerfile
@@ -1,4 +1,4 @@
-FROM …
```
=> chore: fix update script for mac silicon

versions.json
Has not worked since 22 was released.
Closes #2107
=> fix: Drop ppc64le from Node 22 Alpine builds

.github/workflows/automatic-updates.yml, .github/workflows/official-pr.yml
The comment for the bot when it creates the PR isn't working since the Enterprise migration. Trying to set the permissions explicitly to see if that addresses it.
=> ci: Add PR Write permission for official PR

22/alpine3.19/Dockerfile, 22/alpine3.20/Dockerfile, 22/bookworm-slim/Dockerfile, 22/bookworm/Dockerfile, 22/bullseye-slim/Dockerfile, 22/bullseye/Dockerfile, versions.json
Adds the new `jod` codename for the LTS, and closes ##2159
=> feat: Node.js 22.11.0 Jod

build-automation.mjs, functions.sh, update.sh
We keep getting key updates from the update script for unchanged node versions, even when the script passes e.g. `./update.sh 22`. This is due to a regression in https://github.com/nodejs/docker-node/pull/1307 where the `get_versions` function no longer looked at its arguments for which version directories to load.
I also got `./update.sh: line 240: pids[@]: unbound variable`, so I moved its declaration.
I also couldn't resist `Object.keys() -> Object.entires()` since we were accessing the values in the loop
---
This should remove the need for PRs such as https://github.com/nodejs/docker-node/pull/2151, as the script should just update the versions with an actual node version change: https://github.com/nodejs/docker-node/blob/ebd48c9005769889a41fe8b835385d5cab1b485c/build-automation.mjs#L9 …
=> fix: correct update script to support version argument again

docs/BestPractices.md
Systems configured to disallow running images as root aren't able to run images that use user name string values for the `USER` because they can't validate that a named user isn't root. To allow images to run on such systems, use the uid of the user as the value for `USER` instead of the username.
See: https://github.com/kubernetes/kubernetes/pull/56503
The current advice is to use `USER node` which won't work on k8s clusters configured with `MustRunAsNonRoot`. By changing that advice to use the uid instead of the username, images will run with `MustRunAsNonRoot`.
=> docs: Use numeric uid instead of username in Dockerfile

18/bookworm-slim/Dockerfile, 18/bookworm/Dockerfile, 18/bullseye-slim/Dockerfile, 18/bullseye/Dockerfile, 20/alpine3.20/Dockerfile, 20/alpine3.21/Dockerfile, 20/bookworm-slim/Dockerfile, 20/bookworm/Dockerfile, 20/bullseye-slim/Dockerfile, 20/bullseye/Dockerfile, 22/alpine3.20/Dockerfile, 22/alpine3.21/Dockerfile, 22/bookworm-slim/Dockerfile, 22/bookworm/Dockerfile, 22/bullseye-slim/Dockerfile, 22/bullseye/Dockerfile, 23/alpine3.20/Dockerfile, 23/alpine3.21/Dockerfile, 23/bookworm-slim/Dockerfile, 23/bookworm/Dockerfile, 23/bullseye-slim/Dockerfile, 23/bullseye/Dockerfile
Reference:
- https://nodejs.org/en/blog/vulnerability/january-2025-security-releases
- https://nodejs.org/en/blog/release/v18.20.6
- https://nodejs.org/en/blog/release/v20.18.2
- https://nodejs.org/en/blog/release/v22.13.1
- https://nodejs.org/en/blog/release/v23.6.1
Node.js January 2025 security release for v18, v20, v22, and v23
=> Node.js January 2025 security release for v18, v20, v22, and v23

.github/workflows/scorecard.yml
The template uses an old version of the action that GitHub sticks to when trying to update. Replacing with the latest v4 SHA
=> ci: use actions/upload-artifact v4.6.2

versions.json
(as reported in https://github.com/nodejs/docker-node/issues/1885#issuecomment-2427264372)
+ node --version
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by node)
I *believe* this is the correct change, but I'm not 100% sure -- I don't see anything in this repository that writes to `versions.json`, so it appears to be hand-maintained and thus this is the correct change for `stackbrew.js` to generate the appropriate contents.
=> Remove arm32v7 from bullseye variants of Node 23

Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
Remove /tmp/node-compile-cache after smoke tests
The Node.js image, during the build process in the RUN layer, executed Node.js and generated the /tmp/node-compile-cache directory without deleting it. According to subsequent build steps, this directory was deleted in the next RUN, therefore it doesn't exist in the final image (though it's only marked as deleted in the current RUN layer - the original files still reside in the historical layers).
=> Clean cache after smoke test

24/alpine3.20/Dockerfile, 24/alpine3.20/docker-entrypoint.sh, 24/alpine3.21/Dockerfile, 24/alpine3.21/docker-entrypoint.sh, 24/bookworm-slim/Dockerfile, 24/bookworm-slim/docker-entrypoint.sh, 24/bookworm/Dockerfile, 24/bookworm/docker-entrypoint.sh, 24/bullseye-slim/Dockerfile, 24/bullseye-slim/docker-entrypoint.sh, 24/bullseye/Dockerfile, 24/bullseye/docker-entrypoint.sh, versions.json
Adds the v23 major line. Modelled after #2149 and #2071.
See also https://github.com/nodejs/node/pull/57609 and https://nodejs.org/en/blog/release/v24.0.0.
=> feat: Node.js 24.0.0

versions.json
It is no longer supported:
- https://github.com/nodejs/docker-node/issues/2232#issuecomment-2867510141
- https://github.com/nodejs/node/pull/58071
I have no idea if I need to update `architectures` too, but I believe `versions.json` is enough?  Happy to update with pointers though.
=> Remove arm32 from Node 24

20/alpine3.21/Dockerfile, 20/alpine3.22/Dockerfile, 20/bookworm-slim/Dockerfile, 20/bookworm/Dockerfile, 20/bullseye-slim/Dockerfile, 20/bullseye/Dockerfile, 22/alpine3.21/Dockerfile, 22/alpine3.22/Dockerfile, 22/bookworm-slim/Dockerfile, 22/bookworm/Dockerfile, 22/bullseye-slim/Dockerfile, 22/bullseye/Dockerfile, 24/alpine3.21/Dockerfile, 24/alpine3.22/Dockerfile, 24/bookworm-slim/Dockerfile, 24/bookworm/Dockerfile, 24/bullseye-slim/Dockerfile, 24/bullseye/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
This solves for the case of `gpg --recv-keys` receiving enough valid data that it doesn't return a non-zero exit code, but that it also doesn't import a key by explicitly checking afterwards that it did import the key we asked for (so that the fallback to keyserver.ubuntu.com actually happens appropriately for keys whose UID are no longer validated on keys.openpgp.org).
See also:
- https://github.com/nodejs/Release/issues/1110
- https://github.com/nodejs/node/issues/58904
- (especially https://github.com/nodejs/node/issues/58904#issuecomment-3029289637)
=> Update all `gpg --recv-keys` invocations with explicit "did it download" checks
